import {mailConfigured,sendMail} from './mail';
import {verifyGoogleToken} from './google-auth';
import {validPassword,passwordRequirements} from '../app/password-rules';
import {checkPassword,digest,emailKey,hashPassword} from './security';
import {readingDuration,readingTimeLimit,MAX_READING_SECONDS,DAILY_AUDIO_SECONDS} from '../app/reading-duration';
import {readingPassages} from '../app/reading-passages';
import {countryCodes} from '../app/countries';
import {readingAssessment,validateAudio} from './reading-analysis';
import {assessPhonemes,phonemeConfigured} from './phoneme-assessment';
import {validateLocalAssessment} from './local-assessment';
type Env={DB:D1Database;ALLOWED_ORIGIN:string;IP_PEPPER:string;RESEND_API_KEY?:string;MAIL_FROM?:string;SMTP_HOST?:string;SMTP_USER?:string;SMTP_PASSWORD?:string;DEV_MODE?:string;AI_ENABLED?:string;AI?:{run:(model:string,input:any)=>Promise<any>};PHONEME_API_URL?:string;PHONEME_API_TOKEN?:string};
type Row=Record<string,any>;
const packs:Record<string,number>={sprint:5,intensif:10,performance:15};
const empty={user:null,profile:null,notes:[],sessions:[],articles:[],requests:[],entitlements:[],paymentInstructions:''};
class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
function fail(status:number,message:string):never{throw new HttpError(status,message)}
const text=(v:unknown,max=100)=>typeof v==='string'?v.trim().slice(0,max):'';
const now=()=>Date.now();
const id=()=>crypto.randomUUID();
function article(row:Row):Row{const paragraphs=Array.isArray(row.paragraphs)?row.paragraphs:JSON.parse(row.paragraphs);return {...row,paragraphs,minutes:Math.max(1,readingDuration(paragraphs.join(' ')).minutes),words:Array.isArray(row.words)?row.words:JSON.parse(row.words),images:Array.isArray(row.images)?row.images:JSON.parse(row.images||'[]')};}
async function mediaUrl(env:Env,request:Request,mid:string){const expires=now()+3600000;const signature=await digest(env.IP_PEPPER+'|media|'+mid+'|'+expires);return new URL('/media/'+mid,request.url).origin+'/media/'+mid+'?expires='+expires+'&signature='+encodeURIComponent(signature);}
async function hydrateArticle(env:Env,request:Request,row:Row){const a=article(row);return {...a,imageUrl:a.image.startsWith('media:')?await mediaUrl(env,request,a.image.slice(6)):undefined,images:await Promise.all(a.images.map(async(m:Row)=>({...m,url:await mediaUrl(env,request,m.id)})))};}
async function audit(env:Env,user:Row,action:string,target:string){await env.DB.prepare('INSERT INTO audit VALUES (?,?,?,?,?)').bind(id(),user.id,action,target,now()).run()}
function ip(request:Request,env:Env){return request.headers.get('CF-Connecting-IP')||(env.DEV_MODE==='local'?'127.0.0.1':fail(503,'Impossible de vérifier votre réseau. Réessayez.'));}
async function ipHash(request:Request,env:Env){if(!env.IP_PEPPER)fail(503,'Le service de sécurité doit être configuré.');return digest(env.IP_PEPPER+'|'+ip(request,env));}
async function rate(request:Request,env:Env,group:string,limit:number){const bucket=await ipHash(request,env)+':'+group+':'+Math.floor(now()/900000);await env.DB.prepare('INSERT INTO rate_limits VALUES (?,1,?) ON CONFLICT(bucket) DO UPDATE SET count=count+1').bind(bucket,now()+900000).run();const r:any=await env.DB.prepare('SELECT count FROM rate_limits WHERE bucket=?').bind(bucket).first();if(r.count>limit)fail(429,'Trop de tentatives. Réessayez dans 15 minutes.');}
async function userFor(request:Request,env:Env):Promise<Row|null>{const token=request.headers.get('Authorization')?.replace(/^Bearer /,'');if(!token)return null;return env.DB.prepare('SELECT u.* FROM users u JOIN auth_sessions s ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.disabled=0').bind(await digest(token),now()).first<Row>()}
async function login(env:Env,user:Row){const token=id()+id();await env.DB.prepare('INSERT INTO auth_sessions VALUES (?,?,?)').bind(await digest(token),user.id,now()+7*86400000).run();return {token};}
async function activeAccess(env:Env,user:Row){const granted=await env.DB.prepare('SELECT * FROM entitlements WHERE user_id=? AND revoked=0 AND starts_at<=? AND ends_at>?').bind(user.id,now(),now()).all<Row>();if(granted.results.length)return {type:'paid',packs:granted.results.map(e=>e.plan),entitlements:granted.results};const trialActive=!!user.trial_at&&now()-user.trial_at<48*3600000;return {type:trialActive?'trial':'none',packs:trialActive?['trial']:[],entitlements:[]};}
async function allowedArticles(env:Env,user:Row){const access=await activeAccess(env,user);if(!access.packs.length)return [];const rows=await env.DB.prepare(`SELECT DISTINCT a.* FROM articles a JOIN article_packs p ON p.article_id=a.id WHERE a.published=1 AND p.pack IN (${access.packs.map(()=>'?').join(',')}) ORDER BY a.title`).bind(...access.packs).all<Row>();return access.type==='trial'?rows.results.slice(0,1).map(article):rows.results.map(article);}
async function account(env:Env,user:Row|null,request:Request){if(!user)return empty;const [notes,sessions,requests,access,content,instructions]=await Promise.all([env.DB.prepare('SELECT * FROM notes WHERE user_id=? ORDER BY created_at DESC').bind(user.id).all(),env.DB.prepare('SELECT r.*,a.title article_title FROM readings r LEFT JOIN articles a ON a.id=r.article_id WHERE r.user_id=? ORDER BY r.created_at DESC LIMIT 1000').bind(user.id).all(),env.DB.prepare('SELECT * FROM requests WHERE user_id=? ORDER BY created_at DESC').bind(user.id).all(),activeAccess(env,user),allowedArticles(env,user),env.DB.prepare("SELECT value FROM settings WHERE key='payment_instructions'").first<Row>()]);const {password_hash,email_key,google_sub,...profile}=user;return {user:{id:user.id,email:user.email,name:user.first_name,role:user.role,emailVerified:!!user.email_verified,hasPassword:user.password_hash.startsWith('pbkdf2:'),googleLinked:!!user.google_sub},profile:{...profile,user_id:user.id},notes:notes.results,sessions:sessions.results,articles:await Promise.all(content.map(a=>hydrateArticle(env,request,a))),requests:requests.results,entitlements:access.entitlements,accessType:access.type,emailDeliveryEnabled:mailConfigured(env),paymentInstructions:instructions?.value||''};}
async function sendVerification(env:Env,user:Row){if(env.DEV_MODE!=='local'&&!mailConfigured(env))return {verificationPending:true};const token=id()+id();await env.DB.prepare('INSERT INTO verification_tokens VALUES (?,?,?)').bind(await digest(token),user.id,now()+24*3600000).run();if(env.DEV_MODE==='local')return {verificationToken:token};const link=env.ALLOWED_ORIGIN+'/#verification/'+token;try{await sendMail(env,{to:user.email,subject:'Confirmez votre compte MimFlo',text:'Bonjour '+user.first_name+',\n\nConfirmez votre adresse pour activer votre essai unique : '+link+'\n\nCe lien est valable 24 heures. Si vous n’avez pas demandé de compte, ignorez cet e-mail.\n\nL’équipe MimFlo'});return {verificationPending:false};}catch{return {verificationPending:true};}}
async function route(request:Request,env:Env){const url=new URL(request.url),path=url.pathname,method=request.method;const user=await userFor(request,env);let b:Row={},audioBytes:Uint8Array|undefined;if(path==='/analysis'&&method==='POST'){if(!user)fail(401,'Connectez-vous pour analyser votre lecture.');b={id:url.searchParams.get('id'),articleId:url.searchParams.get('articleId'),consent:url.searchParams.get('consent')==='true',passageIndex:Number(url.searchParams.get('passageIndex'))};if(request.headers.get('Content-Type')!=='audio/wav')fail(400,'Format audio invalide.');const max=44+MAX_READING_SECONDS*32000;if(Number(request.headers.get('Content-Length'))>max)fail(413,'Audio trop volumineux.');const reader=request.body?.getReader(),chunks:Uint8Array[]=[];let size=0;if(reader)while(true){const chunk=await reader.read();if(chunk.done)break;size+=chunk.value.length;if(size>max){await reader.cancel();fail(413,'Audio trop volumineux.');}chunks.push(chunk.value);}audioBytes=new Uint8Array(size);let at=0;for(const chunk of chunks){audioBytes.set(chunk,at);at+=chunk.length;}}else if(method==='POST'){const max=path==='/analysis/local'?1200000:path==='/admin/ai-check'?428000:path==='/admin/media'?2200000:100000;if(Number(request.headers.get('Content-Length'))>max)fail(413,'Données trop volumineuses.');const reader=request.body?.getReader();let size=0,raw='',decoder=new TextDecoder();if(reader){while(true){const chunk=await reader.read();if(chunk.done)break;size+=chunk.value.length;if(size>max){await reader.cancel();fail(413,'Données trop volumineuses.');}raw+=decoder.decode(chunk.value,{stream:true});}raw+=decoder.decode();}try{b=JSON.parse(raw)}catch{fail(400,'Données invalides.')}}
 if(path.startsWith('/media/')&&method==='GET'){const mid=path.slice(7),expires=Number(url.searchParams.get('expires'));if(!Number.isFinite(expires)||expires<now()||expires>now()+3600000||url.searchParams.get('signature')!==await digest(env.IP_PEPPER+'|media|'+mid+'|'+expires))fail(403,'Accès à cette image expiré.');const media=await env.DB.prepare('SELECT content,mime FROM media WHERE id=?').bind(mid).first<Row>();if(!media)fail(404,'Image introuvable.');return new Response(new Uint8Array(media.content),{headers:{'Content-Type':media.mime,'Cache-Control':'private, max-age=300','X-Content-Type-Options':'nosniff'}});}
 if(path==='/account'&&method==='GET')return account(env,user,request);
 if(path==='/auth/google/config'&&method==='GET'){const setting=await env.DB.prepare("SELECT value FROM settings WHERE key='google_client_id'").first<Row>();return {enabled:!!setting?.value,clientId:setting?.value||''};}
 if(path==='/auth/google/challenge'&&method==='POST'){
  await rate(request,env,'google-challenge',30);const setting=await env.DB.prepare("SELECT value FROM settings WHERE key='google_client_id'").first<Row>();if(!setting?.value)fail(503,'La connexion Google n’est pas encore configurée.');
  const mode=b.mode;if(!['login','register'].includes(mode)||mode==='register'&&b.consent!==true||typeof b.proof!=='string'||b.proof.length<64||b.proof.length>100)fail(400,'Acceptez les conditions pour vous inscrire avec Google.');
  const cid=id(),nonce=id()+id();await env.DB.prepare('DELETE FROM google_challenges WHERE expires_at<?').bind(now()).run();await env.DB.prepare('INSERT INTO google_challenges VALUES (?,?,?,?,?,?)').bind(cid,nonce,await digest(b.proof),mode,['A1','A2','B1','B2','C1','C2'].includes(b.level)?b.level:'B1',now()+600000).run();return {id:cid,nonce};
 }
 if(path==='/auth/google'&&method==='POST'){
  await rate(request,env,'google-login',20);const challenge=await env.DB.prepare('SELECT * FROM google_challenges WHERE id=? AND expires_at>?').bind(text(b.id,36),now()).first<Row>();if(!challenge||typeof b.proof!=='string'||await digest(b.proof)!==challenge.proof_hash)fail(400,'Cette connexion Google a expiré. Réessayez.');
  const setting=await env.DB.prepare("SELECT value FROM settings WHERE key='google_client_id'").first<Row>();if(!setting?.value)fail(503,'La connexion Google n’est pas encore configurée.');
  let claims;try{claims=await verifyGoogleToken(text(b.credential,12001),setting.value,challenge.nonce)}catch{fail(401,'Google n’a pas pu confirmer votre identité. Réessayez.');}
  const consumed=await env.DB.prepare('DELETE FROM google_challenges WHERE id=? AND expires_at>?').bind(challenge.id,now()).run();if(!consumed.meta.changes)fail(409,'Cette connexion a déjà été utilisée. Réessayez.');
  let u=await env.DB.prepare('SELECT * FROM users WHERE google_sub=?').bind(claims.sub).first<Row>();if(u){if(u.disabled)fail(403,'Ce compte est désactivé. Contactez MimFlo.');return login(env,u);}
  if(await env.DB.prepare('SELECT id FROM users WHERE email_key=?').bind(emailKey(claims.email)).first())fail(409,'Un compte MimFlo existe déjà avec cette adresse. Connectez-vous avec votre e-mail et votre mot de passe.');
  if(challenge.mode!=='register')fail(409,'Aucun compte Google associé. Ouvrez Inscription et acceptez les conditions pour créer votre compte.');
  const uid=id(),verified=claims.email.toLowerCase().endsWith('@gmail.com')||!!claims.hd;try{await env.DB.prepare('INSERT INTO users(id,email,email_key,password_hash,first_name,last_name,level,source,created_at,email_verified,google_sub) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(uid,claims.email,emailKey(claims.email),'google-only',text(claims.given_name||claims.name,60)||'Membre',text(claims.family_name,60),challenge.level,'Google',now(),verified?1:0,claims.sub).run()}catch{fail(409,'Ce compte existe déjà. Recommencez la connexion.');}u=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(uid).first<Row>();return {...await login(env,u!),...(!verified?await sendVerification(env,u!):{})};
 }
 if(path==='/auth/register'&&method==='POST'){await rate(request,env,'register',8);const email=text(b.email,254);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!text(b.firstName,60)||!text(b.lastName,60)||!b.consent)fail(400,'Complétez votre nom, votre e-mail et acceptez les conditions.');if(!validPassword(b.password))fail(400,passwordRequirements);const key=emailKey(email);if(await env.DB.prepare('SELECT id FROM users WHERE email_key=?').bind(key).first())fail(409,'Un compte existe déjà avec cette adresse. Connectez-vous.');const u={id:id(),email,first_name:text(b.firstName,60)};try{await env.DB.prepare('INSERT INTO users(id,email,email_key,password_hash,first_name,last_name,level,exam,source,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(u.id,email,key,await hashPassword(b.password),u.first_name,text(b.lastName,60),['A1','A2','B1','B2','C1','C2'].includes(b.level)?b.level:'B1',text(b.exam,40),text(b.source,80),now()).run()}catch{fail(409,'Un compte existe déjà avec cette adresse.');}return {...await login(env,u),...await sendVerification(env,u)};}
 if(path==='/auth/login'&&method==='POST'){await rate(request,env,'login',20);const u=await env.DB.prepare('SELECT * FROM users WHERE email_key=? AND disabled=0').bind(emailKey(text(b.email,254))).first<Row>();const valid=await checkPassword(typeof b.password==='string'&&b.password.length<=128?b.password:'',u?.password_hash||'pbkdf2:100000:unknown:invalid');if(!u||!valid)fail(401,'E-mail ou mot de passe incorrect.');return login(env,u);}
 if(path==='/auth/verify'&&method==='POST'){await rate(request,env,'verify',15);const hash=await digest(text(b.token,100));const v=await env.DB.prepare('SELECT * FROM verification_tokens WHERE token_hash=? AND expires_at>?').bind(hash,now()).first<Row>();if(!v)fail(400,'Lien expiré ou invalide.');await env.DB.batch([env.DB.prepare('UPDATE users SET email_verified=1 WHERE id=?').bind(v.user_id),env.DB.prepare('DELETE FROM verification_tokens WHERE user_id=?').bind(v.user_id)]);return {ok:true};}
 if(!user)fail(401,'Connectez-vous ou inscrivez-vous pour accéder à votre espace.');
 if(path==='/analysis/status'&&method==='GET'){const access=await activeAccess(env,user),used=access.type==='trial'&&!!await env.DB.prepare("SELECT id FROM analysis_jobs WHERE user_id=? AND access_type='trial' AND status IN ('processing','completed')").bind(user.id).first();return {enabled:true,allowed:access.type!=='none'&&!used,message:used?'Votre analyse offerte a déjà été utilisée. Choisissez un pack pour continuer.':access.type==='none'?'Activez votre essai gratuit ou choisissez un pack pour analyser une lecture.':'',provider:'local-phoneme-ctc',maxSeconds:600,passageWords:30,adaptiveDuration:true};}
 if(path==='/analysis/local'&&method==='POST'){
  if(b.consent!==true)fail(400,'Autorisez l’analyse de votre enregistrement.');
  const jobId=text(b.id,36);if(!/^[a-f0-9-]{36}$/.test(jobId))fail(400,'Identifiant d’analyse invalide.');
  const previous=await env.DB.prepare('SELECT * FROM analysis_jobs WHERE id=? AND user_id=?').bind(jobId,user.id).first<Row>();
  if(previous){if(previous.article_id!==b.articleId||previous.passage_index!==b.passageIndex)fail(409,'Cette analyse appartient à une autre lecture.');if(previous.status==='completed')return JSON.parse(previous.result);fail(409,'Cette analyse est déjà utilisée.');}
  const access=await activeAccess(env,user),a=(await allowedArticles(env,user)).find(a=>a.id===b.articleId);if(!a)fail(403,'Cet article n’est pas inclus dans votre accès actif.');
  const passages=readingPassages(a.paragraphs,access.type==='trial'?30:600);if(!Number.isInteger(b.passageIndex)||b.passageIndex<0||b.passageIndex>=passages.length)fail(400,'Choisissez un passage valide.');
  const seconds=Number(b.seconds),max=access.type==='trial'?30:readingTimeLimit(passages[b.passageIndex]);if(!Number.isFinite(seconds)||seconds<3||seconds>max)fail(400,'La durée dépasse la limite de votre passage.');
  let assessment;try{assessment=validateLocalAssessment(b.analysis,passages[b.passageIndex],seconds,b.passageIndex+1)}catch(e){fail(400,(e as Error).message)}
  await rate(request,env,'local-analysis',30);
  const transcript=assessment.phonemes.filter((p:any)=>p.heard).map((p:any)=>p.heard).join(' '),response={ok:true,id:jobId,transcript,analysis:assessment,coverage:assessment.score,seconds,passageIndex:b.passageIndex};
  try{await env.DB.batch([
   ...(access.type==='trial'?[env.DB.prepare("DELETE FROM readings WHERE user_id=? AND access_type='trial' AND analysis IS NULL").bind(user.id)]:[]),
   env.DB.prepare('INSERT INTO analysis_jobs(id,user_id,article_id,access_type,status,day,created_at,passage_index,audio_seconds,result) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(jobId,user.id,a.id,access.type,'completed',new Date().toISOString().slice(0,10),now(),b.passageIndex,0,JSON.stringify(response)),
   env.DB.prepare('INSERT INTO readings(id,user_id,article_id,seconds,transcript,coverage,access_type,created_at,analysis) VALUES (?,?,?,?,?,?,?,?,?)').bind(jobId,user.id,a.id,Math.round(seconds),transcript,assessment.score,access.type,now(),JSON.stringify(assessment))
  ]);}catch(e){const concurrent=await env.DB.prepare("SELECT result FROM analysis_jobs WHERE id=? AND user_id=? AND status='completed'").bind(jobId,user.id).first<Row>();if(concurrent)return JSON.parse(concurrent.result);fail(409,'Votre analyse offerte a déjà été utilisée ou une autre sauvegarde est en cours.');}
  return response;
 }
 if(path==='/analysis'&&method==='POST'){
  if(env.AI_ENABLED!=='true'||(!env.AI&&!phonemeConfigured(env)))fail(503,'L’analyse IA est en cours d’activation. Votre lecture peut toujours être sauvegardée.');
  if(!b.consent)fail(400,'Autorisez l’analyse de votre enregistrement.');
  const jobId=text(b.id,36);if(!/^[a-f0-9-]{36}$/.test(jobId))fail(400,'Identifiant d’analyse invalide.');
  const previous=await env.DB.prepare('SELECT * FROM analysis_jobs WHERE id=? AND user_id=?').bind(jobId,user.id).first<Row>();
  if(previous){if(previous.article_id!==b.articleId||previous.passage_index!==b.passageIndex)fail(409,'Cette analyse appartient à une autre lecture.');if(previous.status==='completed')return JSON.parse(previous.result);if(previous.status==='processing')fail(409,'L’analyse est encore en cours. Réessayez dans un instant pour consulter son résultat.');fail(409,'Cette analyse a échoué. Relancez une nouvelle analyse.');}
  const access=await activeAccess(env,user),a=(await allowedArticles(env,user)).find(a=>a.id===b.articleId);if(!a)fail(403,'Cet article n’est pas inclus dans votre accès actif.');
  const passages=readingPassages(a.paragraphs,access.type==='trial'?30:600);if(!Number.isInteger(b.passageIndex)||b.passageIndex<0||b.passageIndex>=passages.length)fail(400,'Choisissez un passage valide.');
  let audio;try{audio=validateAudio(audioBytes!,access.type==='trial'?30:readingTimeLimit(passages[b.passageIndex]))}catch(e){fail(400,(e as Error).message)}
  await rate(request,env,'analysis',10);
  const day=new Date().toISOString().slice(0,10),month=day.slice(0,7)+'%';
  await env.DB.prepare("UPDATE analysis_jobs SET status='failed' WHERE status='processing' AND created_at<?").bind(now()-300000).run();
  try{const reservation=await env.DB.prepare("INSERT INTO analysis_jobs(id,user_id,article_id,access_type,status,day,created_at,passage_index,audio_seconds) SELECT ?,?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM analysis_jobs WHERE day=?)<50 AND (SELECT COUNT(*) FROM analysis_jobs WHERE day=? AND user_id=?)<5 AND (SELECT COALESCE(SUM(audio_seconds),0) FROM analysis_jobs WHERE day=?)+?<=? AND (SELECT COALESCE(SUM(audio_seconds),0) FROM analysis_jobs WHERE day LIKE ?)+?<=14400 AND NOT EXISTS (SELECT 1 FROM analysis_jobs WHERE status='processing')").bind(jobId,user.id,a.id,access.type,'processing',day,now(),b.passageIndex,Math.ceil(audio.seconds),day,day,user.id,day,Math.ceil(audio.seconds),DAILY_AUDIO_SECONDS,month,Math.ceil(audio.seconds)).run();if(!reservation.meta.changes){const monthly=await env.DB.prepare('SELECT COALESCE(SUM(audio_seconds),0) seconds FROM analysis_jobs WHERE day LIKE ?').bind(month).first<Row>();if(Number(monthly?.seconds)+Math.ceil(audio.seconds)>14400)fail(429,'Le quota audio gratuit du mois est atteint. Réessayez le mois prochain.');if(await env.DB.prepare("SELECT id FROM analysis_jobs WHERE status='processing' LIMIT 1").first())fail(409,'Une évaluation est en cours. Réessayez dans un instant.');const used=await env.DB.prepare('SELECT COUNT(*) total,COALESCE(SUM(audio_seconds),0) audio_seconds FROM analysis_jobs WHERE day=?').bind(day).first<Row>();fail(429,used?.total>=50||Number(used?.audio_seconds)+Math.ceil(audio.seconds)>DAILY_AUDIO_SECONDS?'Le quota gratuit du jour est atteint. Les analyses reprennent à 00 h UTC.':'Vous avez utilisé vos cinq analyses gratuites du jour. Revenez demain.');}}catch(e){if(e instanceof HttpError)throw e;fail(409,'Une analyse est déjà en cours ou votre analyse offerte a déjà été utilisée.');}
  try{
   let evaluation;
   if(phonemeConfigured(env)) evaluation=await assessPhonemes(env,audio.bytes,passages[b.passageIndex]);
   else {
    const result=await env.AI!.run('@cf/openai/whisper-large-v3-turbo',{audio:{body:new Blob([audio.bytes as BlobPart]).stream(),contentType:'audio/wav'},task:'transcribe',language:'fr',vad_filter:true,condition_on_previous_text:false});
    const transcript=text(result?.text,16000);if(!transcript)throw new Error('NO_SPEECH');
    evaluation={transcript,assessment:readingAssessment(passages[b.passageIndex],transcript,audio.seconds)};
   }
   const transcript=text(evaluation.transcript,16000),assessment={...evaluation.assessment,passage:b.passageIndex+1},seconds=Math.round(audio.seconds),response={ok:true,id:jobId,transcript,analysis:assessment,coverage:assessment.score,seconds,passageIndex:b.passageIndex};
   // Trial uniqueness is also enforced on readings; inference is reserved before running.
   await env.DB.batch([...(access.type==='trial'?[env.DB.prepare("DELETE FROM readings WHERE user_id=? AND access_type='trial' AND analysis IS NULL").bind(user.id)]:[]),env.DB.prepare('INSERT INTO readings(id,user_id,article_id,seconds,transcript,coverage,access_type,created_at,analysis) VALUES (?,?,?,?,?,?,?,?,?)').bind(jobId,user.id,a.id,seconds,transcript,assessment.score,access.type,now(),JSON.stringify(assessment)),env.DB.prepare("UPDATE analysis_jobs SET status='completed',result=? WHERE id=?").bind(JSON.stringify(response),jobId)]);
   return response;
  }catch(e){console.warn('MimFlo AI failure',e instanceof Error?e.message.slice(0,240):'Unknown failure');await env.DB.prepare("UPDATE analysis_jobs SET status='failed' WHERE id=? AND status='processing'").bind(jobId).run();if(String(e).includes('NO_SPEECH'))fail(422,'Aucune parole reconnue. Enregistrez votre lecture dans un endroit calme.');fail(503,'L’analyse IA n’est pas disponible pour le moment ou son quota gratuit est épuisé. Aucun paiement ne sera demandé.');}
 }
 if(path==='/checkout'&&method==='GET'){const setting=await env.DB.prepare("SELECT value FROM settings WHERE key='paypal_email'").first<Row>();const email=setting?.value||'paypal@example.invalid';return {paypalEmail:email,paypalReady:!!setting?.value&&!email.endsWith('.invalid'),customer:{firstName:user.first_name,lastName:user.last_name,email:user.email,level:user.level}};}
 if(path==='/checkout'&&method==='POST'){
  if(!packs[b.plan])fail(400,'Pack invalide.');
  const c=b.customer||{};const customer={firstName:text(c.firstName,60),lastName:text(c.lastName,60),email:user.email,country:text(c.country,2),address:text(c.address,180),address2:text(c.address2,180),city:text(c.city,100),postalCode:text(c.postalCode,20),phone:text(c.phone,30),level:text(c.level,2),exam:text(c.exam,80)};
  if(!customer.firstName||!customer.lastName||!countryCodes.includes(customer.country)||!customer.address||!customer.city||!/^\+?[\d ()-]{6,30}$/.test(customer.phone)||!['A1','A2','B1','B2','C1','C2'].includes(customer.level)||!b.consent)fail(400,'Complétez vos coordonnées et acceptez les conditions de commande.');
  const setting=await env.DB.prepare("SELECT value FROM settings WHERE key='paypal_email'").first<Row>();const paypalEmail=setting?.value||'';const ready=!!paypalEmail&&!paypalEmail.endsWith('.invalid');
  const pending=await env.DB.prepare("SELECT * FROM requests WHERE user_id=? AND status='pending'").bind(user.id).first<Row>();if(pending&&pending.plan!==b.plan)fail(409,'Une autre commande est en attente. Demandez son annulation avant de changer de pack.');
  const orderId=pending?.id||id();
  await env.DB.batch([pending?env.DB.prepare('UPDATE requests SET customer=? WHERE id=?').bind(JSON.stringify(customer),orderId):env.DB.prepare('INSERT INTO requests(id,user_id,plan,created_at,customer) VALUES (?,?,?,?,?)').bind(orderId,user.id,b.plan,now(),JSON.stringify(customer)),env.DB.prepare('UPDATE users SET first_name=?,last_name=?,level=?,exam=?,selected_plan=? WHERE id=?').bind(customer.firstName,customer.lastName,customer.level,customer.exam,b.plan,user.id)]);
  if(!ready)return {id:orderId,paypalReady:false,message:'Votre commande est enregistrée. Le paiement PayPal sera disponible après sa configuration par MimFlo.'};
  const params=new URLSearchParams({cmd:'_xclick',business:paypalEmail,item_name:'MimFlo · Pack '+b.plan,amount:String({sprint:10,intensif:15,performance:20}[b.plan as 'sprint']),currency_code:'USD',invoice:orderId,custom:orderId,no_shipping:'1',charset:'utf-8',return:env.ALLOWED_ORIGIN+'/#commande/'+orderId,cancel_return:env.ALLOWED_ORIGIN+'/#checkout/'+b.plan});
  return {id:orderId,paypalReady:true,paypalUrl:'https://www.paypal.com/cgi-bin/webscr?'+params};
 }
 if(path==='/auth/password'&&method==='POST'){await rate(request,env,'password',5);if(typeof b.currentPassword!=='string'||b.currentPassword.length>128||!await checkPassword(b.currentPassword,user.password_hash))fail(400,'Mot de passe actuel incorrect.');if(!validPassword(b.newPassword))fail(400,passwordRequirements);await env.DB.batch([env.DB.prepare('UPDATE users SET password_hash=? WHERE id=?').bind(await hashPassword(b.newPassword),user.id),env.DB.prepare('DELETE FROM auth_sessions WHERE user_id=?').bind(user.id)]);return {ok:true};}
 if(path==='/auth/logout'&&method==='POST'){await env.DB.prepare('DELETE FROM auth_sessions WHERE token_hash=?').bind(await digest(request.headers.get('Authorization')!.slice(7))).run();return {ok:true};}
 if(path==='/auth/resend'&&method==='POST'){await rate(request,env,'resend',5);return sendVerification(env,user);}
 if(path==='/account'&&method==='POST'){
  if(b.action==='profile'){if(!text(b.firstName,60)||!text(b.lastName,60)||!['A1','A2','B1','B2','C1','C2'].includes(b.level))fail(400,'Profil incomplet.');await env.DB.prepare('UPDATE users SET first_name=?,last_name=?,level=?,exam=?,source=? WHERE id=?').bind(text(b.firstName,60),text(b.lastName,60),b.level,text(b.exam,40),text(b.source,80),user.id).run();return {ok:true};}
  if(b.action==='trial'){if(!user.email_verified)fail(403,'Confirmez votre adresse e-mail avant de démarrer votre essai.');if(user.trial_at||user.trial_used)fail(409,'Votre essai gratuit a déjà été utilisé.');if(!await env.DB.prepare("SELECT a.id FROM articles a JOIN article_packs p ON p.article_id=a.id WHERE a.published=1 AND p.pack='trial' LIMIT 1").first())fail(409,'L’article de l’essai gratuit sera bientôt disponible.');try{await env.DB.batch([env.DB.prepare('INSERT INTO trial_claims VALUES (?,?,?,?)').bind(user.id,user.email_key,await ipHash(request,env),now()),env.DB.prepare('UPDATE users SET trial_at=?,trial_used=1 WHERE id=? AND trial_at IS NULL').bind(now(),user.id)])}catch{fail(409,'Un essai a déjà été activé avec ce compte, cette adresse e-mail ou ce réseau. Contactez MimFlo si vous partagez cette connexion.');}return {ok:true};}
  if(b.action==='plan'){if(!packs[b.plan])fail(400,'Pack invalide.');try{await env.DB.batch([env.DB.prepare('INSERT INTO requests(id,user_id,plan,created_at) VALUES (?,?,?,?)').bind(id(),user.id,b.plan,now()),env.DB.prepare('UPDATE users SET selected_plan=? WHERE id=?').bind(b.plan,user.id)])}catch{fail(409,'Une demande de paiement est déjà en attente.');}return {ok:true};}
  if(b.action==='note'){const word=text(b.word,100),definition=text(b.definition,1000);if(!word||!definition)fail(400,'Mot et définition requis.');await env.DB.prepare('INSERT INTO notes VALUES (?,?,?,?,?)').bind(id(),user.id,word,definition,now()).run();return {ok:true};}
  if(b.action==='deleteNote'){await env.DB.prepare('DELETE FROM notes WHERE id=? AND user_id=?').bind(text(b.id,50),user.id).run();return {ok:true};}
  if(b.action==='deleteSession'){const sessionId=text(b.id,80);if(!sessionId)fail(400,'Séance introuvable.');const result=await env.DB.prepare('DELETE FROM readings WHERE id=? AND user_id=?').bind(sessionId,user.id).run();if(!result.meta.changes)fail(404,'Séance introuvable.');return {ok:true};}
  if(b.action==='session'){const access=await activeAccess(env,user),content=await allowedArticles(env,user),a=content.find(a=>a.id===b.articleId);if(!a)fail(403,'Cet article n’est pas inclus dans votre accès actif.');if(access.type==='trial'&&await env.DB.prepare("SELECT id FROM analysis_jobs WHERE user_id=? AND status='processing' AND access_type='trial'").bind(user.id).first())fail(409,'Votre analyse est en cours. Attendez son résultat avant de sauvegarder une autre séance.');const seconds=Math.round(Number(b.seconds));if(!Number.isFinite(seconds)||seconds<3||seconds>1800)fail(400,'La séance doit durer entre 3 secondes et 30 minutes.');const transcript=text(b.transcript,16000),norm=(s:string):string[]=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').match(/[a-z]+/g)||[];const expected=norm(a.paragraphs.join(' ')),spoken=norm(transcript);let found=0,j=0;for(const word of expected){const at=spoken.indexOf(word,j);if(at>=0){found++;j=at+1;}}const coverage=transcript&&expected.length?Math.round(found/expected.length*100):null;if(b.analysis)fail(400,'Utilisez la sauvegarde phonétique pour une lecture analysée.');if(access.type==='trial'&&await env.DB.prepare("SELECT id FROM analysis_jobs WHERE user_id=? AND access_type='trial' AND status IN ('processing','completed')").bind(user.id).first())fail(409,'Votre analyse offerte a déjà été utilisée.');const analysis=null;const sessionId=id();try{await env.DB.prepare('INSERT INTO readings(id,user_id,article_id,seconds,transcript,coverage,access_type,created_at,analysis) VALUES (?,?,?,?,?,?,?,?,?)').bind(sessionId,user.id,a.id,seconds,transcript,coverage,access.type,now(),analysis).run()}catch{fail(409,'Votre séance offerte est déjà sauvegardée.');}return {ok:true,id:sessionId,coverage};}
  fail(400,'Action inconnue.');
 }
 if(path.startsWith('/admin')){if(!['admin','owner'].includes(user.role))fail(403,'Accès administrateur requis.');
  if(path==='/admin/ai-check'&&method==='POST'){
   if(user.role!=='owner')fail(403,'Vérification réservée au propriétaire.');if(env.AI_ENABLED!=='true'||(!env.AI&&!phonemeConfigured(env)))fail(503,'Évaluation désactivée.');
   if(!b.consent||typeof b.audio!=='string'||b.audio.length>427000)fail(400,'Échantillon de contrôle et consentement requis.');
   let audio;try{const raw=atob(b.audio),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);audio=validateAudio(bytes);}catch{fail(400,'Échantillon WAV invalide.');}if(audio.seconds>10)fail(400,'Le contrôle est limité à dix secondes.');
   const bucket='ai-check:'+new Date().toISOString().slice(0,10),reserved=await env.DB.prepare('INSERT INTO rate_limits(bucket,count,expires_at) VALUES (?,1,?) ON CONFLICT(bucket) DO UPDATE SET count=count+1 WHERE count<5').bind(bucket,now()+2*86400000).run();if(!reserved.meta.changes)fail(429,'Les cinq contrôles gratuits du jour ont été utilisés.');
   try{if(phonemeConfigured(env)){const result=await assessPhonemes(env,audio.bytes,'Bonjour, nous apprenons le français ensemble.');return {ok:true,transcript:result.transcript,analysis:result.assessment};}const result=await env.AI!.run('@cf/openai/whisper-large-v3-turbo',{audio:{body:new Blob([audio.bytes as BlobPart]).stream(),contentType:'audio/wav'},task:'transcribe',language:'fr',vad_filter:true,condition_on_previous_text:false});const transcript=text(result?.text,16000);return {ok:true,transcript,analysis:readingAssessment('Bonjour, nous apprenons le français ensemble.',transcript,audio.seconds)};}catch(e){console.warn('MimFlo AI check failed',e instanceof Error?e.message.slice(0,240):'Unknown failure');fail(503,'Le service d’évaluation ne répond pas au contrôle.');}
  }
  if(path==='/admin/media'&&method==='POST'){
   await rate(request,env,'media',60);const match=typeof b.data==='string'?b.data.match(/^data:image\/(webp|png|jpeg);base64,([A-Za-z0-9+/=]+)$/):null;if(!match)fail(400,'Format accepté : JPEG, PNG ou WebP.');let bytes:Uint8Array;try{bytes=Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0));}catch{fail(400,'Image invalide.');}if(bytes.length>1500000||bytes.length<12)fail(413,'L’image doit peser moins de 1,5 Mo après optimisation.');const valid=match[1]==='webp'?String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP':match[1]==='png'?bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71:bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!valid)fail(400,'Le contenu de l’image ne correspond pas à son format.');const mid=id();await env.DB.prepare('INSERT INTO media VALUES (?,?,?,?,?,?)').bind(mid,bytes.buffer,'image/'+match[1],text(b.name,160),user.id,now()).run();await audit(env,user,'upload-image',mid);return {id:mid,url:await mediaUrl(env,request,mid),name:text(b.name,160)};
  }
  if(path==='/admin/mail-test'&&method==='POST'){if(user.role!=='owner')fail(403,'Réservé au propriétaire.');if(b.confirmSend!==true)fail(400,'Confirmez l’envoi de l’e-mail de test.');if(!mailConfigured(env))fail(503,'Ajoutez le secret SMTP_PASSWORD dans Cloudflare pour activer l’envoi.');await rate(request,env,'mail-test',3);try{await sendMail(env,{to:env.SMTP_USER||'contact@mimflo.com',subject:'MimFlo — test de l’envoi des e-mails',text:'Votre serveur MimFlo peut envoyer les confirmations d’inscription avec la boîte contact@mimflo.com. Cet e-mail ne contient aucun identifiant ni mot de passe.'});}catch{fail(503,'L’envoi SMTP a échoué. Vérifiez le mot de passe et les paramètres LWS.');}await audit(env,user,'test-email-delivery',env.SMTP_USER||'contact@mimflo.com');return {ok:true};}
  if(path==='/admin/overview'&&method==='GET'){const [users,requests,content,audits,instructions]=await Promise.all([env.DB.prepare('SELECT id,email,first_name,last_name,role,email_verified,disabled,created_at,trial_at,trial_used,selected_plan FROM users ORDER BY created_at DESC').all(),env.DB.prepare('SELECT r.*,u.email,u.first_name,u.last_name FROM requests r JOIN users u ON u.id=r.user_id ORDER BY r.created_at DESC').all(),env.DB.prepare('SELECT * FROM articles ORDER BY updated_at DESC').all<Row>(),env.DB.prepare('SELECT * FROM audit ORDER BY created_at DESC LIMIT 200').all(),env.DB.prepare("SELECT value FROM settings WHERE key='payment_instructions'").first<Row>()]);const links=await env.DB.prepare('SELECT * FROM article_packs').all<Row>();return {users:users.results,requests:requests.results,articles:await Promise.all(content.results.map(async a=>({...await hydrateArticle(env,request,a),packs:links.results.filter(p=>p.article_id===a.id).map(p=>p.pack)}))),categories:(await env.DB.prepare('SELECT name FROM categories ORDER BY name').all()).results.map((c:any)=>c.name),googleClientId:(await env.DB.prepare("SELECT value FROM settings WHERE key='google_client_id'").first<Row>())?.value||'',paypalEmail:(await env.DB.prepare("SELECT value FROM settings WHERE key='paypal_email'").first<Row>())?.value||'paypal@example.invalid',audit:audits.results,paymentInstructions:instructions?.value,emailConfigured:mailConfigured(env)};}
  if(path.startsWith('/admin/client/')&&method==='GET'){const u=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(decodeURIComponent(path.slice(14))).first<Row>();if(!u)fail(404,'Client introuvable.');return account(env,u,request);}
  if(path==='/admin/action'&&method==='POST'){
   if(b.action==='accountStatus'){const target=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(text(b.userId,50)).first<Row>();if(!target||target.role==='owner'||target.id===user.id)fail(403,'Le compte propriétaire ne peut pas être supprimé.');if(target.role==='admin'&&user.role!=='owner')fail(403,'Seul le propriétaire peut gérer les administrateurs.');await env.DB.batch([env.DB.prepare('UPDATE users SET disabled=? WHERE id=?').bind(b.restore?0:1,target.id),env.DB.prepare('DELETE FROM auth_sessions WHERE user_id=?').bind(target.id)]);await audit(env,user,b.restore?'restore-account':'archive-account',target.id);return {ok:true};}
   if(b.action==='google'){if(user.role!=='owner')fail(403,'Seul le propriétaire peut configurer Google.');const clientId=text(b.clientId,200);if(clientId&&!/^[0-9]+-[a-zA-Z0-9_-]+\.apps\.googleusercontent\.com$/.test(clientId))fail(400,'Identifiant client Google invalide.');await env.DB.prepare("INSERT INTO settings VALUES ('google_client_id',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(clientId).run();await audit(env,user,'configure-google','settings');return {ok:true};}
   if(b.action==='paypal'){if(user.role!=='owner')fail(403,'Seul le propriétaire peut configurer PayPal.');const email=text(b.email,254);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'Adresse PayPal invalide.');await env.DB.prepare("INSERT INTO settings VALUES ('paypal_email',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(email).run();await audit(env,user,'configure-paypal','settings');return {ok:true};}
   if(b.action==='review'){const r=await env.DB.prepare('SELECT * FROM requests WHERE id=?').bind(text(b.id,50)).first<Row>();if(!r||r.status!=='pending')fail(409,'Cette demande a déjà été traitée.');if(b.approve){if(!b.paymentChecked||!text(b.reference,120))fail(400,'Confirmez le paiement et indiquez une référence de vérification.');await env.DB.batch([env.DB.prepare("INSERT INTO entitlements SELECT ?,user_id,id,plan,?,?,0,? FROM requests WHERE id=? AND status='pending'").bind(id(),now(),now()+packs[r.plan]*86400000,user.id,r.id),env.DB.prepare("UPDATE requests SET status='approved',reviewed_at=?,reviewed_by=?,reference=? WHERE id=? AND status='pending'").bind(now(),user.id,text(b.reference,120),r.id)]);}else await env.DB.prepare("UPDATE requests SET status='rejected',reviewed_at=?,reviewed_by=? WHERE id=? AND status='pending'").bind(now(),user.id,r.id).run();await audit(env,user,b.approve?'approve-payment':'reject-payment',r.user_id);return {ok:true};}
   if(b.action==='article'){const a=b.article||{},aid=text(a.id,50)||id(),title=text(a.title,160),paragraphs=Array.isArray(a.paragraphs)?a.paragraphs.map((p:any)=>text(p,8000)).filter(Boolean).slice(0,30):[];if(!title||!paragraphs.length||!['A1','A2','B1','B2','C1','C2'].includes(a.level))fail(400,'Titre, niveau et texte sont requis.');const wordPairs=Array.isArray(a.words)?a.words.slice(0,50).map((w:any)=>[text(w[0],100),text(w[1],1000)]):[],chosen=Array.isArray(a.packs)?[...new Set<string>(a.packs)].filter(p=>p==='trial'||packs[p]):[];if(chosen.includes('trial')&&await env.DB.prepare("SELECT article_id FROM article_packs WHERE pack='trial' AND article_id<>?").bind(aid).first())fail(409,'Un article est déjà affecté à l’essai : retirez cette affectation avant d’en choisir un autre.');const minutes=Math.max(1,readingDuration(paragraphs.join(' ')).minutes);const image=/^(media:[a-f0-9-]{36}|[a-zA-Z0-9_.-]+)$/.test(a.image||'')?a.image:'environment.webp';const images=Array.isArray(a.images)?a.images.slice(0,8).map((m:any)=>({id:text(m.id,36),caption:text(m.caption,200),afterParagraph:Math.max(-1,Math.min(paragraphs.length-1,Math.round(Number(m.afterParagraph)||0)))})):[];const mediaIds=[...new Set<string>([...(image.startsWith('media:')?[image.slice(6)]:[]),...images.map((m:any)=>m.id)])];for(const mid of mediaIds)if(!await env.DB.prepare('SELECT id FROM media WHERE id=?').bind(mid).first())fail(400,'Image introuvable. Téléversez-la de nouveau.');const category=text(a.category,80)||'Société';await env.DB.batch([env.DB.prepare('INSERT INTO articles(id,title,category,level,minutes,image,intro,paragraphs,words,published,updated_at,images) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,category=excluded.category,level=excluded.level,minutes=excluded.minutes,image=excluded.image,intro=excluded.intro,paragraphs=excluded.paragraphs,words=excluded.words,published=excluded.published,updated_at=excluded.updated_at,images=excluded.images').bind(aid,title,category,a.level,minutes,image,text(a.intro,1200),JSON.stringify(paragraphs),JSON.stringify(wordPairs),a.published?1:0,now(),JSON.stringify(images)),env.DB.prepare('INSERT OR IGNORE INTO categories(name) VALUES (?)').bind(category),env.DB.prepare('DELETE FROM article_packs WHERE article_id=?').bind(aid),...chosen.map(pack=>env.DB.prepare('INSERT INTO article_packs VALUES (?,?)').bind(aid,pack))]);await audit(env,user,'save-article',aid);return {ok:true};}
   if(b.action==='settings'){await env.DB.prepare("UPDATE settings SET value=? WHERE key='payment_instructions'").bind(text(b.paymentInstructions,3000)).run();await audit(env,user,'payment-instructions','settings');return {ok:true};}
   if(b.action==='verifyEmail'){const target=await env.DB.prepare('SELECT id FROM users WHERE id=? AND role=?').bind(text(b.userId,50),'client').first();if(!target||!b.confirmed)fail(400,'Confirmez avoir vérifié cette adresse avec le client.');await env.DB.prepare('UPDATE users SET email_verified=1 WHERE id=?').bind(b.userId).run();await audit(env,user,'manual-email-verification',b.userId);return {ok:true};}
   if(b.action==='revoke'){await env.DB.prepare('UPDATE entitlements SET revoked=1 WHERE id=?').bind(text(b.id,50)).run();await audit(env,user,'revoke-access',text(b.id,50));return {ok:true};}
   if(b.action==='createAccount'){if(user.role!=='owner')fail(403,'Seul le propriétaire peut créer des administrateurs.');const role=b.role==='admin'?'admin':'client',email=text(b.email,254);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!text(b.firstName,60)||!text(b.lastName,60))fail(400,'Nom et e-mail requis.');if(!validPassword(b.password))fail(400,passwordRequirements);const uid=id();try{await env.DB.prepare('INSERT INTO users(id,email,email_key,password_hash,role,email_verified,first_name,last_name,created_at) VALUES (?,?,?,?,?,1,?,?,?)').bind(uid,email,emailKey(email),await hashPassword(b.password),role,text(b.firstName,60),text(b.lastName,60),now()).run()}catch{fail(409,'Cette adresse possède déjà un compte.');}await audit(env,user,'create-'+role,uid);return {ok:true};}
   fail(400,'Action administrateur inconnue.');
  }
 }
 fail(404,'Page introuvable.');
}
export default {async fetch(request:Request,env:Env){const origin=request.headers.get('Origin'),allowed=origin===env.ALLOWED_ORIGIN||(env.DEV_MODE==='local'&&origin==='http://127.0.0.1:4173');const headers={'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':allowed?origin!:'null','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Vary':'Origin','X-Content-Type-Options':'nosniff'};if(request.method==='OPTIONS')return new Response(null,{status:allowed?204:403,headers});if(request.method!=='GET'&&!allowed)return new Response(JSON.stringify({error:'Origine refusée.'}),{status:403,headers});try{const result=await route(request,env);if(result instanceof Response)return result;return new Response(JSON.stringify(result),{headers})}catch(e){return new Response(JSON.stringify({error:e instanceof HttpError?e.message:'Le service est indisponible. Réessayez.'}),{status:e instanceof HttpError?e.status:503,headers})}},async scheduled(_:unknown,env:Env){await env.DB.batch([env.DB.prepare('DELETE FROM auth_sessions WHERE expires_at<?').bind(now()),env.DB.prepare('DELETE FROM verification_tokens WHERE expires_at<?').bind(now()),env.DB.prepare('DELETE FROM rate_limits WHERE expires_at<?').bind(now()),env.DB.prepare('DELETE FROM google_challenges WHERE expires_at<?').bind(now())]);}};
