import {checkPassword,digest,emailKey,hashPassword} from './security';
import {countryCodes} from '../app/countries';
type Env={DB:D1Database;ALLOWED_ORIGIN:string;IP_PEPPER:string;RESEND_API_KEY?:string;MAIL_FROM?:string;DEV_MODE?:string};
type Row=Record<string,any>;
const packs:Record<string,number>={sprint:5,intensif:10,performance:15};
const empty={user:null,profile:null,notes:[],sessions:[],articles:[],requests:[],entitlements:[],paymentInstructions:''};
class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
function fail(status:number,message:string):never{throw new HttpError(status,message)}
const text=(v:unknown,max=100)=>typeof v==='string'?v.trim().slice(0,max):'';
const now=()=>Date.now();
const id=()=>crypto.randomUUID();
function article(row:Row):Row{return {...row,paragraphs:Array.isArray(row.paragraphs)?row.paragraphs:JSON.parse(row.paragraphs),words:Array.isArray(row.words)?row.words:JSON.parse(row.words),images:Array.isArray(row.images)?row.images:JSON.parse(row.images||'[]')};}
async function mediaUrl(env:Env,request:Request,mid:string){const expires=now()+3600000;const signature=await digest(env.IP_PEPPER+'|media|'+mid+'|'+expires);return new URL('/media/'+mid,request.url).origin+'/media/'+mid+'?expires='+expires+'&signature='+encodeURIComponent(signature);}
async function hydrateArticle(env:Env,request:Request,row:Row){const a=article(row);return {...a,imageUrl:a.image.startsWith('media:')?await mediaUrl(env,request,a.image.slice(6)):undefined,images:await Promise.all(a.images.map(async(m:Row)=>({...m,url:await mediaUrl(env,request,m.id)})))};}
async function audit(env:Env,user:Row,action:string,target:string){await env.DB.prepare('INSERT INTO audit VALUES (?,?,?,?,?)').bind(id(),user.id,action,target,now()).run()}
function ip(request:Request,env:Env){return request.headers.get('CF-Connecting-IP')||(env.DEV_MODE==='local'?'127.0.0.1':fail(503,'Impossible de vérifier votre réseau. Réessayez.'));}
async function ipHash(request:Request,env:Env){if(!env.IP_PEPPER)fail(503,'Le service de sécurité doit être configuré.');return digest(env.IP_PEPPER+'|'+ip(request,env));}
async function rate(request:Request,env:Env,group:string,limit:number){const bucket=await ipHash(request,env)+':'+group+':'+Math.floor(now()/900000);await env.DB.prepare('INSERT INTO rate_limits VALUES (?,1,?) ON CONFLICT(bucket) DO UPDATE SET count=count+1').bind(bucket,now()+900000).run();const r:any=await env.DB.prepare('SELECT count FROM rate_limits WHERE bucket=?').bind(bucket).first();if(r.count>limit)fail(429,'Trop de tentatives. Réessayez dans 15 minutes.');}
async function userFor(request:Request,env:Env):Promise<Row|null>{const token=request.headers.get('Authorization')?.replace(/^Bearer /,'');if(!token)return null;return env.DB.prepare('SELECT u.* FROM users u JOIN auth_sessions s ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.disabled=0').bind(await digest(token),now()).first<Row>()}
async function login(env:Env,user:Row){const token=id()+id();await env.DB.prepare('INSERT INTO auth_sessions VALUES (?,?,?)').bind(await digest(token),user.id,now()+7*86400000).run();return {token};}
async function activeAccess(env:Env,user:Row){const granted=await env.DB.prepare('SELECT * FROM entitlements WHERE user_id=? AND revoked=0 AND starts_at<=? AND ends_at>?').bind(user.id,now(),now()).all<Row>();if(granted.results.length)return {type:'paid',packs:granted.results.map(e=>e.plan),entitlements:granted.results};const used:any=await env.DB.prepare("SELECT count(*) total FROM readings WHERE user_id=? AND access_type='trial'").bind(user.id).first();return {type:user.trial_at&&now()-user.trial_at<48*3600000&&!used.total?'trial':'none',packs:user.trial_at&&now()-user.trial_at<48*3600000&&!used.total?['trial']:[],entitlements:[]};}
async function allowedArticles(env:Env,user:Row){const access=await activeAccess(env,user);if(!access.packs.length)return [];const rows=await env.DB.prepare(`SELECT DISTINCT a.* FROM articles a JOIN article_packs p ON p.article_id=a.id WHERE a.published=1 AND p.pack IN (${access.packs.map(()=>'?').join(',')}) ORDER BY a.title`).bind(...access.packs).all<Row>();return access.type==='trial'?rows.results.slice(0,1).map(article):rows.results.map(article);}
async function account(env:Env,user:Row|null,request:Request){if(!user)return empty;const [notes,sessions,requests,access,content,instructions]=await Promise.all([env.DB.prepare('SELECT * FROM notes WHERE user_id=? ORDER BY created_at DESC').bind(user.id).all(),env.DB.prepare('SELECT * FROM readings WHERE user_id=? ORDER BY created_at DESC LIMIT 1000').bind(user.id).all(),env.DB.prepare('SELECT * FROM requests WHERE user_id=? ORDER BY created_at DESC').bind(user.id).all(),activeAccess(env,user),allowedArticles(env,user),env.DB.prepare("SELECT value FROM settings WHERE key='payment_instructions'").first<Row>()]);const {password_hash,email_key,...profile}=user;return {user:{id:user.id,email:user.email,name:user.first_name,role:user.role,emailVerified:!!user.email_verified},profile:{...profile,user_id:user.id},notes:notes.results,sessions:sessions.results,articles:await Promise.all(content.map(a=>hydrateArticle(env,request,a))),requests:requests.results,entitlements:access.entitlements,accessType:access.type,paymentInstructions:instructions?.value||''};}
async function sendVerification(env:Env,user:Row){const token=id()+id();await env.DB.prepare('INSERT INTO verification_tokens VALUES (?,?,?)').bind(await digest(token),user.id,now()+24*3600000).run();if(env.DEV_MODE==='local')return {verificationToken:token};if(!env.RESEND_API_KEY||!env.MAIL_FROM)return {verificationPending:true};const link=env.ALLOWED_ORIGIN+'/mimflo.github.io/#verification/'+token;const result=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+env.RESEND_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({from:env.MAIL_FROM,to:user.email,subject:'Confirmez votre compte MimFlo',text:'Confirmez votre adresse pour activer votre essai unique : '+link})});return {verificationPending:!result.ok};}
async function route(request:Request,env:Env){const url=new URL(request.url),path=url.pathname,method=request.method;const user=await userFor(request,env);let b:Row={};if(method==='POST'){const raw=await request.text();if(raw.length>(path==='/admin/media'?2200000:100000))fail(413,'Données trop volumineuses.');try{b=JSON.parse(raw)}catch{fail(400,'Données invalides.')}}
 if(path.startsWith('/media/')&&method==='GET'){const mid=path.slice(7),expires=Number(url.searchParams.get('expires'));if(!Number.isFinite(expires)||expires<now()||expires>now()+3600000||url.searchParams.get('signature')!==await digest(env.IP_PEPPER+'|media|'+mid+'|'+expires))fail(403,'Accès à cette image expiré.');const media=await env.DB.prepare('SELECT content,mime FROM media WHERE id=?').bind(mid).first<Row>();if(!media)fail(404,'Image introuvable.');return new Response(new Uint8Array(media.content),{headers:{'Content-Type':media.mime,'Cache-Control':'private, max-age=300','X-Content-Type-Options':'nosniff'}});}
 if(path==='/account'&&method==='GET')return account(env,user,request);
 if(path==='/auth/register'&&method==='POST'){await rate(request,env,'register',8);const email=text(b.email,254);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!text(b.firstName,60)||!text(b.lastName,60)||!b.consent)fail(400,'Complétez votre nom, votre e-mail et acceptez les conditions.');if(typeof b.password!=='string'||b.password.length<12||b.password.length>128)fail(400,'Choisissez un mot de passe entre 12 et 128 caractères.');const key=emailKey(email);if(await env.DB.prepare('SELECT id FROM users WHERE email_key=?').bind(key).first())fail(409,'Un compte existe déjà avec cette adresse. Connectez-vous.');const u={id:id(),email,first_name:text(b.firstName,60)};try{await env.DB.prepare('INSERT INTO users(id,email,email_key,password_hash,first_name,last_name,level,exam,source,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(u.id,email,key,await hashPassword(b.password),u.first_name,text(b.lastName,60),['A1','A2','B1','B2','C1','C2'].includes(b.level)?b.level:'B1',text(b.exam,40),text(b.source,80),now()).run()}catch{fail(409,'Un compte existe déjà avec cette adresse.');}return {...await login(env,u),...await sendVerification(env,u)};}
 if(path==='/auth/login'&&method==='POST'){await rate(request,env,'login',20);const u=await env.DB.prepare('SELECT * FROM users WHERE email_key=? AND disabled=0').bind(emailKey(text(b.email,254))).first<Row>();const valid=await checkPassword(typeof b.password==='string'&&b.password.length<=128?b.password:'',u?.password_hash||'pbkdf2:100000:unknown:invalid');if(!u||!valid)fail(401,'E-mail ou mot de passe incorrect.');return login(env,u);}
 if(path==='/auth/verify'&&method==='POST'){await rate(request,env,'verify',15);const hash=await digest(text(b.token,100));const v=await env.DB.prepare('SELECT * FROM verification_tokens WHERE token_hash=? AND expires_at>?').bind(hash,now()).first<Row>();if(!v)fail(400,'Lien expiré ou invalide.');await env.DB.batch([env.DB.prepare('UPDATE users SET email_verified=1 WHERE id=?').bind(v.user_id),env.DB.prepare('DELETE FROM verification_tokens WHERE user_id=?').bind(v.user_id)]);return {ok:true};}
 if(!user)fail(401,'Connectez-vous ou inscrivez-vous pour accéder à votre espace.');
 if(path==='/checkout'&&method==='GET'){const setting=await env.DB.prepare("SELECT value FROM settings WHERE key='paypal_email'").first<Row>();const email=setting?.value||'paypal@example.invalid';return {paypalEmail:email,paypalReady:!!setting?.value&&!email.endsWith('.invalid'),customer:{firstName:user.first_name,lastName:user.last_name,email:user.email,level:user.level}};}
 if(path==='/checkout'&&method==='POST'){
  if(!packs[b.plan])fail(400,'Pack invalide.');
  const c=b.customer||{};const customer={firstName:text(c.firstName,60),lastName:text(c.lastName,60),email:user.email,country:text(c.country,2),address:text(c.address,180),address2:text(c.address2,180),city:text(c.city,100),postalCode:text(c.postalCode,20),phone:text(c.phone,30),level:text(c.level,2),exam:text(c.exam,80)};
  if(!customer.firstName||!customer.lastName||!countryCodes.includes(customer.country)||!customer.address||!customer.city||!/^\+?[\d ()-]{6,30}$/.test(customer.phone)||!['A1','A2','B1','B2','C1','C2'].includes(customer.level)||!b.consent)fail(400,'Complétez vos coordonnées et acceptez les conditions de commande.');
  const setting=await env.DB.prepare("SELECT value FROM settings WHERE key='paypal_email'").first<Row>();const paypalEmail=setting?.value||'';const ready=!!paypalEmail&&!paypalEmail.endsWith('.invalid');
  const pending=await env.DB.prepare("SELECT * FROM requests WHERE user_id=? AND status='pending'").bind(user.id).first<Row>();if(pending&&pending.plan!==b.plan)fail(409,'Une autre commande est en attente. Demandez son annulation avant de changer de pack.');
  const orderId=pending?.id||id();
  await env.DB.batch([pending?env.DB.prepare('UPDATE requests SET customer=? WHERE id=?').bind(JSON.stringify(customer),orderId):env.DB.prepare('INSERT INTO requests(id,user_id,plan,created_at,customer) VALUES (?,?,?,?,?)').bind(orderId,user.id,b.plan,now(),JSON.stringify(customer)),env.DB.prepare('UPDATE users SET first_name=?,last_name=?,level=?,exam=?,selected_plan=? WHERE id=?').bind(customer.firstName,customer.lastName,customer.level,customer.exam,b.plan,user.id)]);
  if(!ready)return {id:orderId,paypalReady:false,message:'Votre commande est enregistrée. Le paiement PayPal sera disponible après sa configuration par MimFlo.'};
  const params=new URLSearchParams({cmd:'_xclick',business:paypalEmail,item_name:'MimFlo · Pack '+b.plan,amount:String({sprint:10,intensif:15,performance:20}[b.plan as 'sprint']),currency_code:'USD',invoice:orderId,custom:orderId,no_shipping:'1',charset:'utf-8',return:env.ALLOWED_ORIGIN+'/mimflo.github.io/#commande/'+orderId,cancel_return:env.ALLOWED_ORIGIN+'/mimflo.github.io/#checkout/'+b.plan});
  return {id:orderId,paypalReady:true,paypalUrl:'https://www.paypal.com/cgi-bin/webscr?'+params};
 }
 if(path==='/auth/password'&&method==='POST'){await rate(request,env,'password',5);if(typeof b.currentPassword!=='string'||b.currentPassword.length>128||!await checkPassword(b.currentPassword,user.password_hash))fail(400,'Mot de passe actuel incorrect.');if(typeof b.newPassword!=='string'||b.newPassword.length<12||b.newPassword.length>128)fail(400,'Choisissez un mot de passe entre 12 et 128 caractères.');await env.DB.batch([env.DB.prepare('UPDATE users SET password_hash=? WHERE id=?').bind(await hashPassword(b.newPassword),user.id),env.DB.prepare('DELETE FROM auth_sessions WHERE user_id=?').bind(user.id)]);return {ok:true};}
 if(path==='/auth/logout'&&method==='POST'){await env.DB.prepare('DELETE FROM auth_sessions WHERE token_hash=?').bind(await digest(request.headers.get('Authorization')!.slice(7))).run();return {ok:true};}
 if(path==='/auth/resend'&&method==='POST'){await rate(request,env,'resend',5);return sendVerification(env,user);}
 if(path==='/account'&&method==='POST'){
  if(b.action==='profile'){if(!text(b.firstName,60)||!text(b.lastName,60)||!['A1','A2','B1','B2','C1','C2'].includes(b.level))fail(400,'Profil incomplet.');await env.DB.prepare('UPDATE users SET first_name=?,last_name=?,level=?,exam=?,source=? WHERE id=?').bind(text(b.firstName,60),text(b.lastName,60),b.level,text(b.exam,40),text(b.source,80),user.id).run();return {ok:true};}
  if(b.action==='trial'){if(!user.email_verified)fail(403,'Confirmez votre adresse e-mail avant de démarrer votre essai.');if(user.trial_at||user.trial_used)fail(409,'Votre essai gratuit a déjà été utilisé.');if(!await env.DB.prepare("SELECT a.id FROM articles a JOIN article_packs p ON p.article_id=a.id WHERE a.published=1 AND p.pack='trial' LIMIT 1").first())fail(409,'L’article de l’essai gratuit sera bientôt disponible.');try{await env.DB.batch([env.DB.prepare('INSERT INTO trial_claims VALUES (?,?,?,?)').bind(user.id,user.email_key,await ipHash(request,env),now()),env.DB.prepare('UPDATE users SET trial_at=?,trial_used=1 WHERE id=? AND trial_at IS NULL').bind(now(),user.id)])}catch{fail(409,'Un essai a déjà été activé avec ce compte, cette adresse e-mail ou ce réseau. Contactez MimFlo si vous partagez cette connexion.');}return {ok:true};}
  if(b.action==='plan'){if(!packs[b.plan])fail(400,'Pack invalide.');try{await env.DB.batch([env.DB.prepare('INSERT INTO requests(id,user_id,plan,created_at) VALUES (?,?,?,?)').bind(id(),user.id,b.plan,now()),env.DB.prepare('UPDATE users SET selected_plan=? WHERE id=?').bind(b.plan,user.id)])}catch{fail(409,'Une demande de paiement est déjà en attente.');}return {ok:true};}
  if(b.action==='note'){const word=text(b.word,100),definition=text(b.definition,1000);if(!word||!definition)fail(400,'Mot et définition requis.');await env.DB.prepare('INSERT INTO notes VALUES (?,?,?,?,?)').bind(id(),user.id,word,definition,now()).run();return {ok:true};}
  if(b.action==='deleteNote'){await env.DB.prepare('DELETE FROM notes WHERE id=? AND user_id=?').bind(text(b.id,50),user.id).run();return {ok:true};}
  if(b.action==='session'){const access=await activeAccess(env,user),content=await allowedArticles(env,user),a=content.find(a=>a.id===b.articleId);if(!a)fail(403,'Cet article n’est pas inclus dans votre accès actif.');const seconds=Math.round(Number(b.seconds));if(!Number.isFinite(seconds)||seconds<3||seconds>1800)fail(400,'La séance doit durer entre 3 secondes et 30 minutes.');const transcript=text(b.transcript,16000),norm=(s:string):string[]=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').match(/[a-z]+/g)||[];const expected=norm(a.paragraphs.join(' ')),spoken=norm(transcript);let found=0,j=0;for(const word of expected){const at=spoken.indexOf(word,j);if(at>=0){found++;j=at+1;}}const coverage=transcript&&expected.length?Math.round(found/expected.length*100):null;try{await env.DB.prepare('INSERT INTO readings VALUES (?,?,?,?,?,?,?,?)').bind(id(),user.id,a.id,seconds,transcript,coverage,access.type,now()).run()}catch{fail(409,'Votre séance offerte est déjà sauvegardée.');}return {ok:true,coverage};}
  fail(400,'Action inconnue.');
 }
 if(path.startsWith('/admin')){if(!['admin','owner'].includes(user.role))fail(403,'Accès administrateur requis.');
  if(path==='/admin/media'&&method==='POST'){
   await rate(request,env,'media',60);const match=typeof b.data==='string'?b.data.match(/^data:image\/(webp|png|jpeg);base64,([A-Za-z0-9+/=]+)$/):null;if(!match)fail(400,'Format accepté : JPEG, PNG ou WebP.');let bytes:Uint8Array;try{bytes=Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0));}catch{fail(400,'Image invalide.');}if(bytes.length>1500000||bytes.length<12)fail(413,'L’image doit peser moins de 1,5 Mo après optimisation.');const valid=match[1]==='webp'?String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP':match[1]==='png'?bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71:bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!valid)fail(400,'Le contenu de l’image ne correspond pas à son format.');const mid=id();await env.DB.prepare('INSERT INTO media VALUES (?,?,?,?,?,?)').bind(mid,bytes.buffer,'image/'+match[1],text(b.name,160),user.id,now()).run();await audit(env,user,'upload-image',mid);return {id:mid,url:await mediaUrl(env,request,mid),name:text(b.name,160)};
  }
  if(path==='/admin/overview'&&method==='GET'){const [users,requests,content,audits,instructions]=await Promise.all([env.DB.prepare('SELECT id,email,first_name,last_name,role,email_verified,disabled,created_at,trial_at,trial_used,selected_plan FROM users ORDER BY created_at DESC').all(),env.DB.prepare('SELECT r.*,u.email,u.first_name,u.last_name FROM requests r JOIN users u ON u.id=r.user_id ORDER BY r.created_at DESC').all(),env.DB.prepare('SELECT * FROM articles ORDER BY updated_at DESC').all<Row>(),env.DB.prepare('SELECT * FROM audit ORDER BY created_at DESC LIMIT 200').all(),env.DB.prepare("SELECT value FROM settings WHERE key='payment_instructions'").first<Row>()]);const links=await env.DB.prepare('SELECT * FROM article_packs').all<Row>();return {users:users.results,requests:requests.results,articles:await Promise.all(content.results.map(async a=>({...await hydrateArticle(env,request,a),packs:links.results.filter(p=>p.article_id===a.id).map(p=>p.pack)}))),categories:(await env.DB.prepare('SELECT name FROM categories ORDER BY name').all()).results.map((c:any)=>c.name),paypalEmail:(await env.DB.prepare("SELECT value FROM settings WHERE key='paypal_email'").first<Row>())?.value||'paypal@example.invalid',audit:audits.results,paymentInstructions:instructions?.value,emailConfigured:!!env.RESEND_API_KEY};}
  if(path.startsWith('/admin/client/')&&method==='GET'){const u=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(decodeURIComponent(path.slice(14))).first<Row>();if(!u)fail(404,'Client introuvable.');return account(env,u,request);}
  if(path==='/admin/action'&&method==='POST'){
   if(b.action==='accountStatus'){const target=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(text(b.userId,50)).first<Row>();if(!target||target.role==='owner'||target.id===user.id)fail(403,'Le compte propriétaire ne peut pas être supprimé.');if(target.role==='admin'&&user.role!=='owner')fail(403,'Seul le propriétaire peut gérer les administrateurs.');await env.DB.batch([env.DB.prepare('UPDATE users SET disabled=? WHERE id=?').bind(b.restore?0:1,target.id),env.DB.prepare('DELETE FROM auth_sessions WHERE user_id=?').bind(target.id)]);await audit(env,user,b.restore?'restore-account':'archive-account',target.id);return {ok:true};}
   if(b.action==='paypal'){if(user.role!=='owner')fail(403,'Seul le propriétaire peut configurer PayPal.');const email=text(b.email,254);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'Adresse PayPal invalide.');await env.DB.prepare("INSERT INTO settings VALUES ('paypal_email',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(email).run();await audit(env,user,'configure-paypal','settings');return {ok:true};}
   if(b.action==='review'){const r=await env.DB.prepare('SELECT * FROM requests WHERE id=?').bind(text(b.id,50)).first<Row>();if(!r||r.status!=='pending')fail(409,'Cette demande a déjà été traitée.');if(b.approve){if(!b.paymentChecked||!text(b.reference,120))fail(400,'Confirmez le paiement et indiquez une référence de vérification.');await env.DB.batch([env.DB.prepare("INSERT INTO entitlements SELECT ?,user_id,id,plan,?,?,0,? FROM requests WHERE id=? AND status='pending'").bind(id(),now(),now()+packs[r.plan]*86400000,user.id,r.id),env.DB.prepare("UPDATE requests SET status='approved',reviewed_at=?,reviewed_by=?,reference=? WHERE id=? AND status='pending'").bind(now(),user.id,text(b.reference,120),r.id)]);}else await env.DB.prepare("UPDATE requests SET status='rejected',reviewed_at=?,reviewed_by=? WHERE id=? AND status='pending'").bind(now(),user.id,r.id).run();await audit(env,user,b.approve?'approve-payment':'reject-payment',r.user_id);return {ok:true};}
   if(b.action==='article'){const a=b.article||{},aid=text(a.id,50)||id(),title=text(a.title,160),paragraphs=Array.isArray(a.paragraphs)?a.paragraphs.map((p:any)=>text(p,8000)).filter(Boolean).slice(0,30):[];if(!title||!paragraphs.length||!['A1','A2','B1','B2','C1','C2'].includes(a.level))fail(400,'Titre, niveau et texte sont requis.');const wordPairs=Array.isArray(a.words)?a.words.slice(0,50).map((w:any)=>[text(w[0],100),text(w[1],1000)]):[],chosen=Array.isArray(a.packs)?[...new Set<string>(a.packs)].filter(p=>p==='trial'||packs[p]):[];if(chosen.includes('trial')&&await env.DB.prepare("SELECT article_id FROM article_packs WHERE pack='trial' AND article_id<>?").bind(aid).first())fail(409,'Un article est déjà affecté à l’essai : retirez cette affectation avant d’en choisir un autre.');const minutes=Math.round(Number(a.minutes));if(!Number.isFinite(minutes)||minutes<1||minutes>60)fail(400,'Durée invalide.');const image=/^(media:[a-f0-9-]{36}|[a-zA-Z0-9_.-]+)$/.test(a.image||'')?a.image:'environment.webp';const images=Array.isArray(a.images)?a.images.slice(0,8).map((m:any)=>({id:text(m.id,36),caption:text(m.caption,200),afterParagraph:Math.max(-1,Math.min(paragraphs.length-1,Math.round(Number(m.afterParagraph)||0)))})):[];const mediaIds=[...new Set<string>([...(image.startsWith('media:')?[image.slice(6)]:[]),...images.map((m:any)=>m.id)])];for(const mid of mediaIds)if(!await env.DB.prepare('SELECT id FROM media WHERE id=?').bind(mid).first())fail(400,'Image introuvable. Téléversez-la de nouveau.');const category=text(a.category,80)||'Société';await env.DB.batch([env.DB.prepare('INSERT INTO articles(id,title,category,level,minutes,image,intro,paragraphs,words,published,updated_at,images) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,category=excluded.category,level=excluded.level,minutes=excluded.minutes,image=excluded.image,intro=excluded.intro,paragraphs=excluded.paragraphs,words=excluded.words,published=excluded.published,updated_at=excluded.updated_at,images=excluded.images').bind(aid,title,category,a.level,minutes,image,text(a.intro,1200),JSON.stringify(paragraphs),JSON.stringify(wordPairs),a.published?1:0,now(),JSON.stringify(images)),env.DB.prepare('INSERT OR IGNORE INTO categories(name) VALUES (?)').bind(category),env.DB.prepare('DELETE FROM article_packs WHERE article_id=?').bind(aid),...chosen.map(pack=>env.DB.prepare('INSERT INTO article_packs VALUES (?,?)').bind(aid,pack))]);await audit(env,user,'save-article',aid);return {ok:true};}
   if(b.action==='settings'){await env.DB.prepare("UPDATE settings SET value=? WHERE key='payment_instructions'").bind(text(b.paymentInstructions,3000)).run();await audit(env,user,'payment-instructions','settings');return {ok:true};}
   if(b.action==='verifyEmail'){const target=await env.DB.prepare('SELECT id FROM users WHERE id=? AND role=?').bind(text(b.userId,50),'client').first();if(!target||!b.confirmed)fail(400,'Confirmez avoir vérifié cette adresse avec le client.');await env.DB.prepare('UPDATE users SET email_verified=1 WHERE id=?').bind(b.userId).run();await audit(env,user,'manual-email-verification',b.userId);return {ok:true};}
   if(b.action==='revoke'){await env.DB.prepare('UPDATE entitlements SET revoked=1 WHERE id=?').bind(text(b.id,50)).run();await audit(env,user,'revoke-access',text(b.id,50));return {ok:true};}
   if(b.action==='createAccount'){if(user.role!=='owner')fail(403,'Seul le propriétaire peut créer des administrateurs.');const role=b.role==='admin'?'admin':'client',email=text(b.email,254);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!text(b.firstName,60)||!text(b.lastName,60)||typeof b.password!=='string'||b.password.length<12||b.password.length>128)fail(400,'Nom, e-mail et mot de passe de 12 caractères minimum requis.');const uid=id();try{await env.DB.prepare('INSERT INTO users(id,email,email_key,password_hash,role,email_verified,first_name,last_name,created_at) VALUES (?,?,?,?,?,1,?,?,?)').bind(uid,email,emailKey(email),await hashPassword(b.password),role,text(b.firstName,60),text(b.lastName,60),now()).run()}catch{fail(409,'Cette adresse possède déjà un compte.');}await audit(env,user,'create-'+role,uid);return {ok:true};}
   fail(400,'Action administrateur inconnue.');
  }
 }
 fail(404,'Page introuvable.');
}
export default {async fetch(request:Request,env:Env){const origin=request.headers.get('Origin'),allowed=origin===env.ALLOWED_ORIGIN||(env.DEV_MODE==='local'&&origin==='http://127.0.0.1:4173');const headers={'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':allowed?origin!:'null','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Vary':'Origin','X-Content-Type-Options':'nosniff'};if(request.method==='OPTIONS')return new Response(null,{status:allowed?204:403,headers});if(request.method!=='GET'&&!allowed)return new Response(JSON.stringify({error:'Origine refusée.'}),{status:403,headers});try{const result=await route(request,env);if(result instanceof Response)return result;return new Response(JSON.stringify(result),{headers})}catch(e){return new Response(JSON.stringify({error:e instanceof HttpError?e.message:'Le service est indisponible. Réessayez.'}),{status:e instanceof HttpError?e.status:503,headers})}},async scheduled(_:unknown,env:Env){await env.DB.batch([env.DB.prepare('DELETE FROM auth_sessions WHERE expires_at<?').bind(now()),env.DB.prepare('DELETE FROM verification_tokens WHERE expires_at<?').bind(now()),env.DB.prepare('DELETE FROM rate_limits WHERE expires_at<?').bind(now())]);}};
