import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFile,mkdir,writeFile,readdir} from 'node:fs/promises';
import ts from 'typescript';
// Real SQLite constraints and real request handler; inference is a deterministic mock.
const output=new URL('../.qa/ai-tests/',import.meta.url);await mkdir(output,{recursive:true});
for(const [source,name] of [['backend/security.ts','security'],['app/countries.ts','countries'],['app/reading-passages.ts','reading-passages'],['backend/reading-analysis.ts','reading-analysis'],['backend/index.ts','index']]){
 let code=ts.transpileModule(await readFile(source,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
 code=code.replaceAll("'./security'","'./security.mjs'").replaceAll("'../app/countries'","'./countries.mjs'").replaceAll("'../app/reading-passages'","'./reading-passages.mjs'").replaceAll("'./reading-analysis'","'./reading-analysis.mjs'");await writeFile(new URL(name+'.mjs',output),code);
}
const {default:worker}=await import(new URL('index.mjs',output));const {digest}=await import(new URL('security.mjs',output));const {readingAssessment}=await import(new URL('reading-analysis.mjs',output));
const sql=new DatabaseSync(':memory:');for(const file of (await readdir('backend/migrations')).filter(f=>f.endsWith('.sql')).sort())sql.exec(await readFile('backend/migrations/'+file,'utf8'));
function prepared(query,args=[]){return {query,args,bind(...params){return prepared(query,params)},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){const result=sql.prepare(query).run(...args);return {meta:{changes:Number(result.changes)}}}}}
const DB={prepare:prepared,async batch(items){sql.exec('BEGIN');try{const results=[];for(const item of items)results.push(await item.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e}}};
let calls=0,failInference=false,hold=false,release;const env={DB,ALLOWED_ORIGIN:'https://renolix.github.io',IP_PEPPER:'qa-pepper',DEV_MODE:'local',AI_ENABLED:'true',AI:{async run(model,input){calls++;assert.equal(model,'@cf/openai/whisper-large-v3-turbo');assert.equal(input.language,'fr');assert.equal(input.audio.contentType,'audio/wav');assert.equal(new TextDecoder().decode((await new Response(input.audio.body).arrayBuffer()).slice(0,4)),'RIFF');if(hold)await new Promise(r=>release=r);if(failInference)throw new Error('quota');return {text:'Bonjour nous apprenons le français ensemble.'}}}};
async function user(name,trial=false){const token=crypto.randomUUID();sql.prepare('INSERT INTO users(id,email,email_key,password_hash,first_name,last_name,created_at,trial_at,email_verified) VALUES (?,?,?,?,?,?,?,?,1)').run(name,name+'@example.com',name,'unused',name,'QA',Date.now(),trial?Date.now():null);sql.prepare('INSERT INTO auth_sessions VALUES (?,?,?)').run(await digest(token),name,Date.now()+60000);if(!trial)sql.prepare('INSERT INTO entitlements VALUES (?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),name,null,'sprint',Date.now()-1000,Date.now()+60000,0,'qa');return token}
sql.prepare('INSERT INTO articles(id,title,category,level,minutes,intro,paragraphs,updated_at,published) VALUES (?,?,?,?,?,?,?,?,1)').run('article','Lecture QA','Société','B1',2,'',JSON.stringify(['Bonjour nous apprenons le français ensemble.']),Date.now());for(const p of ['sprint','trial'])sql.prepare('INSERT INTO article_packs VALUES (?,?)').run('article',p);
const paid=await user('paid'),trial=await user('trial',true),guest=await user('no-access');sql.prepare('DELETE FROM entitlements WHERE user_id=?').run('no-access');
function wav(seconds=4,silent=false){const b=new Uint8Array(44+Math.round(seconds*32000)),v=new DataView(b.buffer),tag=(at,s)=>{for(let i=0;i<s.length;i++)b[at+i]=s.charCodeAt(i)};tag(0,'RIFF');v.setUint32(4,b.length-8,true);tag(8,'WAVE');tag(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);tag(36,'data');v.setUint32(40,b.length-44,true);if(!silent)for(let i=44;i<b.length;i+=2)v.setInt16(i,Math.sin(i*.013)*6000,true);return b}
async function req(token,{id=crypto.randomUUID(),body=wav(),consent=true,articleId='article',passageIndex=0,origin=env.ALLOWED_ORIGIN}={}){const request=new Request('https://qa.example/analysis?'+new URLSearchParams({id,articleId,consent:String(consent),passageIndex:String(passageIndex)}),{method:'POST',headers:{Origin:origin,'Content-Type':'audio/wav',...(token?{Authorization:'Bearer '+token}:{})},body});const result=await worker.fetch(request,env);return {status:result.status,data:await result.json(),id}}
assert.equal((await req()).status,401);assert.equal((await req(paid,{origin:'https://evil.example'})).status,403);assert.equal((await req(guest)).status,403);assert.equal((await req(paid,{consent:false})).status,400);assert.equal((await req(paid,{body:new Uint8Array(100)})).status,400);assert.equal((await req(paid,{body:wav(4,true)})).status,400);assert.equal((await req(paid,{body:wav(121)})).status,413);assert.equal((await req(paid,{passageIndex:10})).status,400);assert.equal(calls,0);
const result=await req(paid);assert.equal(result.status,200);assert.equal(result.data.analysis.score,100);assert.equal(result.data.analysis.kind,'reading');const replay=await req(paid,{id:result.id});assert.equal(replay.status,200);assert.equal(calls,1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM readings').get().n,1);
const edits=readingAssessment('Bonjour le monde bonjour','Bonjour monde monde',4);assert.ok(edits.score<100);assert.equal(edits.missing+edits.different+edits.added,2);assert.equal(readingAssessment('été','ete',4).score,0,'Preserve French accents, do not hide differences');
hold=true;const first=req(trial);while(!release)await new Promise(r=>setTimeout(r,1));assert.equal((await req(trial)).status,409);hold=false;release();assert.equal((await first).status,200);assert.equal((await req(trial)).status,403,'Trial consumed by its single saved analysis');
for(let i=0;i<4;i++)assert.equal((await req(paid)).status,200);assert.equal((await req(paid)).status,429,'Per-user cap');
const other=await user('failure');failInference=true;assert.equal((await req(other)).status,503);failInference=false;assert.equal(sql.prepare("SELECT COUNT(*) n FROM analysis_jobs WHERE status='failed'").get().n,1,'Failures keep their quota reservation');
const day=new Date().toISOString().slice(0,10);for(let i=Number(sql.prepare('SELECT COUNT(*) n FROM analysis_jobs WHERE day=?').get(day).n);i<50;i++)sql.prepare('INSERT INTO analysis_jobs(id,user_id,article_id,access_type,status,day,created_at) VALUES (?,?,?,?,?,?,?)').run(crypto.randomUUID(),'failure','article','paid','failed',day+'-old-'+i,Date.now()); // Move fixtures to today without running inference.
sql.prepare('UPDATE analysis_jobs SET day=? WHERE day<>?').run(day,day);assert.equal((await req(other)).status,429,'Global daily cap');
const owner=await user('owner');sql.prepare("UPDATE users SET role='owner' WHERE id='owner'").run();
async function health(token){const response=await worker.fetch(new Request('https://qa.example/admin/ai-check',{method:'POST',headers:{Origin:env.ALLOWED_ORIGIN,'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({audio:Buffer.from(wav()).toString('base64'),consent:true})}),env);return response.status}
assert.equal(await health(paid),403);for(let i=0;i<5;i++)assert.equal(await health(owner),200);assert.equal(await health(owner),429,'Diagnostic is owner-only and capped at five short calls/day');
const before=calls;env.AI_ENABLED='false';assert.equal((await req(other)).status,503);assert.equal(calls,before);
console.log('PASS: audio validation, consent, auth and access, French differences, saved assessment, idempotency, concurrent single trial, per-user and global quotas, failures and kill switch. No external AI calls.');


