import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const base=process.env.MIMFLO_TEST_API||'http://127.0.0.1:8787';
assert.ok(['127.0.0.1','localhost'].includes(new URL(base).hostname));
const credentials=await readFile('outputs/mimflo-admin-identifiants.txt','utf8');
const network='198.19.'+Math.floor(Math.random()*255)+'.'+Math.floor(Math.random()*255);
async function req(path,body,token){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{Origin:'http://127.0.0.1:4173','CF-Connecting-IP':network,...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};}
const owner=(await req('/auth/login',{email:credentials.match(/E-mail : (.+)/)[1],password:credentials.match(/Mot de passe : (.+)/)[1]})).data.token;
assert.ok(owner);
const suffix=Date.now();const profile={email:`checkout-${suffix}@example.com`,password:'ClientTestSecure!12345',firstName:'Client',lastName:'Test',consent:true,level:'B1'};
const client=(await req('/auth/register',profile)).data.token;assert.ok(client);
const uid=(await req('/account',undefined,client)).data.user.id;
assert.equal((await req('/checkout',{plan:'sprint',customer:{}},undefined)).status,401,'Checkout requires an account');
assert.equal((await req('/checkout',{plan:'sprint',customer:{}},client)).status,400);
const customer={firstName:'Client',lastName:'Test',country:'DZ',address:'1 rue du Test',city:'Alger',postalCode:'16000',phone:'+213555000000',level:'B2',exam:'TCF'};
assert.equal((await req('/checkout',{plan:'sprint',customer:{...customer,country:'XX'},consent:true},client)).status,400);
await req('/admin/action',{action:'paypal',email:'paypal@example.invalid'},owner);
const order=await req('/checkout',{plan:'sprint',customer,consent:true,amount:1},client);assert.equal(order.status,200);assert.equal(order.data.paypalReady,false);assert.equal(order.data.paypalUrl,undefined);
assert.equal((await req('/checkout',{plan:'sprint',customer,consent:true},client)).data.id,order.data.id,'Retry does not create duplicate orders');
assert.equal((await req('/account',undefined,client)).data.articles.length,0);
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aL1sAAAAASUVORK5CYII=';
assert.equal((await req('/admin/media',{data:png},client)).status,403);
assert.equal((await req('/admin/media',{data:'data:image/svg+xml;base64,PHN2Zz48L3N2Zz4='},owner)).status,400);
const upload=await req('/admin/media',{data:png,name:'photo.png'},owner);assert.equal(upload.status,200);assert.ok(upload.data.id);
const image=await fetch(upload.data.url);assert.equal(image.status,200);assert.equal(image.headers.get('Content-Type'),'image/png');assert.ok((await image.arrayBuffer()).byteLength>0);
assert.equal((await fetch(base+'/media/'+upload.data.id)).status,403);
const imageUrl=new URL(upload.data.url);imageUrl.searchParams.set('expires','1');assert.equal((await fetch(imageUrl)).status,403);
const article={id:'media-test-'+suffix,title:'Lecture illustrée',category:'Nouvelle thématique '+suffix,level:'B1',minutes:8,image:'media:'+upload.data.id,intro:'Une introduction',paragraphs:['Premier paragraphe.','Deuxième paragraphe.'],words:[],packs:['sprint'],published:true,images:[{id:upload.data.id,caption:'Une image',afterParagraph:0}]};
assert.equal((await req('/admin/action',{action:'article',article},owner)).status,200);
let overview=(await req('/admin/overview',undefined,owner)).data;assert.ok(overview.categories.includes(article.category));assert.equal(JSON.parse(overview.requests.find(r=>r.id===order.data.id).customer).country,'DZ');
assert.equal((await req('/admin/action',{action:'review',id:order.data.id,approve:true,paymentChecked:true,reference:'LOCAL-TEST-PAYPAL'},owner)).status,200);
let paid=(await req('/account',undefined,client)).data;let saved=paid.articles.find(a=>a.id===article.id);assert.ok(saved.imageUrl);assert.equal(saved.images[0].caption,'Une image');assert.equal(saved.images[0].afterParagraph,0);
assert.equal((await req('/admin/action',{action:'article',article:{...article,title:'Lecture modifiée',images:[{id:upload.data.id,caption:'Nouvelle légende',afterParagraph:-1}]}},owner)).status,200);
saved=(await req('/account',undefined,client)).data.articles.find(a=>a.id===article.id);assert.equal(saved.title,'Lecture modifiée');assert.equal(saved.images[0].afterParagraph,-1);
assert.equal((await req('/admin/action',{action:'accountStatus',userId:uid},client)).status,403);
const ownerId=(await req('/account',undefined,owner)).data.user.id;assert.equal((await req('/admin/action',{action:'accountStatus',userId:ownerId},owner)).status,403);
assert.equal((await req('/admin/action',{action:'accountStatus',userId:uid},owner)).status,200);
assert.equal((await req('/account',undefined,client)).data.user,null);
assert.equal((await req('/auth/login',{email:profile.email,password:profile.password})).status,401);
assert.equal((await req('/admin/action',{action:'accountStatus',userId:uid,restore:true},owner)).status,200);
assert.equal((await req('/auth/login',{email:profile.email,password:profile.password})).status,200);
// Inspect PayPal URL only: no navigation, charge or payment is performed.
await req('/admin/action',{action:'paypal',email:'merchant@example.com'},owner);
const relogin=(await req('/auth/login',{email:profile.email,password:profile.password})).data.token;
const payable=await req('/checkout',{plan:'sprint',customer,consent:true,amount:1},relogin);
assert.equal(new URL(payable.data.paypalUrl).hostname,'www.paypal.com');assert.equal(new URL(payable.data.paypalUrl).searchParams.get('amount'),'10');
await req('/admin/action',{action:'paypal',email:'paypal@example.invalid'},owner);
console.log('PASS: authenticated checkout, server prices, dummy PayPal, order details, private media upload, article editing, persistent topics, account deletion/restore, owner protection.');
