import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const base=process.env.MIMFLO_TEST_API||'http://127.0.0.1:8787';
assert.ok(['127.0.0.1','localhost'].includes(new URL(base).hostname),'Run these disposable tests only against localhost');
const origin=process.env.MIMFLO_TEST_ORIGIN||'http://127.0.0.1:4173';
const testNetwork='198.18.'+Math.floor(Math.random()*255)+'.'+Math.floor(Math.random()*255);
const credentials=await readFile('outputs/mimflo-admin-identifiants.txt','utf8');
const email=credentials.match(/E-mail : (.+)/)[1],password=credentials.match(/Mot de passe : (.+)/)[1];
async function req(path,body,token,network=testNetwork){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':network,...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()}}
const guest=await req('/account');assert.equal(guest.data.user,null);assert.deepEqual(guest.data.articles,[]);
const admin=await req('/auth/login',{email,password});assert.equal(admin.status,200);const owner=admin.data.token;
const suffix=Date.now(),clientEmail=`mimflo.qa.${suffix}@gmail.com`,form={email:clientEmail,password:'TestClientSafe!9274',firstName:'Test',lastName:'Client',level:'B1',consent:true};
const registered=await req('/auth/register',form);assert.equal(registered.status,200);const client=registered.data.token;
const alias=await req('/auth/register',{...form,email:`mimfloqa${suffix}+duplicate@googlemail.com`});assert.equal(alias.status,409,'Gmail aliases cannot create another account');
assert.equal((await req('/admin/overview',undefined,client)).status,403);
assert.equal((await req('/account',{action:'trial'},client)).status,403,'Unverified email cannot use trial');
assert.equal((await req('/auth/verify',{token:registered.data.verificationToken},client)).status,200);
const articleId='test-'+suffix,content={id:articleId,title:'Article de contrôle',category:'Société',level:'B1',minutes:5,intro:'Contrôle des autorisations.',paragraphs:['Bonjour nous apprenons le français ensemble.'],words:[['ensemble','Avec les autres.']],published:true,packs:['trial','sprint']};
// Only one article may be assigned to the trial: remove the prior QA assignment if rerun.
const overview=await req('/admin/overview',undefined,owner);
for(const a of overview.data.articles.filter(a=>a.packs.includes('trial'))){await req('/admin/action',{action:'article',article:{...a,packs:a.packs.filter(p=>p!=='trial')}},owner)}
assert.equal((await req('/admin/action',{action:'article',article:content},owner)).status,200);
assert.deepEqual((await req('/account',undefined,client)).data.articles,[],'No text before entitlement');
assert.equal((await req('/account',{action:'trial'},client)).status,200);
assert.equal((await req('/account',{action:'trial'},client)).status,409);
assert.equal((await req('/account',undefined,client)).data.articles.length,1);
const second=await req('/auth/register',{...form,email:`other-${suffix}@example.com`},undefined);
await req('/auth/verify',{token:second.data.verificationToken},second.data.token);
assert.equal((await req('/account',{action:'trial'},second.data.token)).status,409,'Same IP cannot activate a second trial');
assert.equal((await req('/account',{action:'session',articleId:'not-granted',seconds:20},client)).status,403);
assert.equal((await req('/account',{action:'session',articleId,seconds:20,transcript:'Bonjour nous apprenons le français ensemble.'},client)).status,200);
assert.deepEqual((await req('/account',undefined,client)).data.articles,[],'Free access closes after first reading');
assert.equal((await req('/account',{action:'session',articleId,seconds:20},client)).status,403);
await req('/account',{action:'plan',plan:'sprint'},client);
assert.deepEqual((await req('/account',undefined,client)).data.articles,[],'Pending payment grants no access');
const pending=(await req('/admin/overview',undefined,owner)).data.requests.find(r=>r.user_id===(registered.data.userId||undefined))||(await req('/account',undefined,client)).data.requests[0];
assert.equal((await req('/admin/action',{action:'review',id:pending.id,approve:true},owner)).status,400);
assert.equal((await req('/admin/action',{action:'review',id:pending.id,approve:true,paymentChecked:true,reference:'LOCAL-QA-ONLY'},owner)).status,200);
const paid=(await req('/account',undefined,client)).data;assert.equal(paid.accessType,'paid');assert.ok(paid.articles.some(a=>a.id===articleId));assert.equal(paid.entitlements.length,1);
assert.equal((await req('/account',{action:'session',articleId,seconds:30},client)).status,200,'Paid clients may save more readings');
const dossier=await req('/admin/client/'+paid.user.id,undefined,owner);assert.equal(dossier.status,200);assert.equal(dossier.data.sessions.length,2);
assert.equal((await req('/admin/action',{action:'createAccount',role:'admin',email:`intruder-${suffix}@example.com`,password:'TestSafePassword123',firstName:'A',lastName:'B'},client)).status,403);
assert.equal((await req('/admin/action',{action:'createAccount',role:'admin',email:`team-${suffix}@example.com`,password:'TestSafePassword123',firstName:'A',lastName:'B'},owner)).status,200);
assert.equal((await req('/auth/password',{currentPassword:'incorrect',newPassword:'NewTestClientSafe!9274'},client)).status,400);
assert.equal((await req('/auth/password',{currentPassword:form.password,newPassword:'NewTestClientSafe!9274'},client)).status,200);
assert.equal((await req('/admin/overview',undefined,client)).status,401,'Password change revokes sessions');
assert.equal((await req('/auth/login',{email:form.email,password:form.password})).status,401);
assert.equal((await req('/auth/login',{email:form.email,password:'NewTestClientSafe!9274'})).status,200);
console.log('PASS: guest protection, Gmail aliases, email verification, IP reuse, unique trial, article permissions, payment approval, paid readings, client dossier, admin roles and password rotation.');
