import assert from 'node:assert/strict';import {readFile,writeFile,mkdir} from 'node:fs/promises';import ts from 'typescript';
await mkdir('.qa/mail-tests',{recursive:true});await writeFile('.qa/mail-tests/mail.mjs',ts.transpileModule(await readFile('backend/mail.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);const {sendSmtp,mailConfigured}=await import('../.qa/mail-tests/mail.mjs');
const env={SMTP_HOST:'mail01.lwspanel.com',SMTP_USER:'contact@mimflo.com',SMTP_PASSWORD:'test-only-not-a-secret',MAIL_FROM:'contact@mimflo.com'};
function fixture(rejectAuth=false){let control,closed=false,index=0;const sent=[];const replies=['250-mail QA\r\n250 AUTH LOGIN\r\n','334 user\r\n','334 password\r\n',rejectAuth?'535 rejected\r\n':'235 OK\r\n','250 sender\r\n','250 receiver\r\n','354 continue\r\n','250 queued\r\n'];return {sent,get closed(){return closed},connect(address,options){assert.equal(address.port,465);assert.equal(address.hostname,env.SMTP_HOST);assert.equal(options.secureTransport,'on');return {opened:Promise.resolve(),readable:new ReadableStream({start(c){control=c;c.enqueue(new TextEncoder().encode('220 Ready\r\n'));}}),writable:new WritableStream({write(bytes){sent.push(new TextDecoder().decode(bytes));control.enqueue(new TextEncoder().encode(replies[index++]));}}),async close(){closed=true;control.close()}}}}}
assert.equal(mailConfigured(env),true);assert.equal(mailConfigured({...env,SMTP_PASSWORD:''}),false);
const good=fixture();await sendSmtp(good.connect,env,{to:'client@example.test',subject:'Confirmez votre compte MimFlo',text:'Bonjour, confirmez votre compte.\nhttps://example.test/#verification/test-only'});assert.equal(good.closed,true);assert.equal(good.sent[0],'EHLO mimflo.com\r\n');assert.equal(good.sent[1],'AUTH LOGIN\r\n');assert.equal(good.sent[3],btoa(env.SMTP_PASSWORD)+'\r\n');const message=good.sent[7];assert.ok(message.includes('Content-Transfer-Encoding: base64'));assert.ok(message.endsWith('\r\n.\r\n'));assert.ok(!message.includes(env.SMTP_PASSWORD));
const rejected=fixture(true);await assert.rejects(()=>sendSmtp(rejected.connect,env,{to:'client@example.test',subject:'Test',text:'Test'}),/535/);assert.equal(rejected.closed,true);assert.equal(rejected.sent.length,4);
await assert.rejects(()=>sendSmtp(good.connect,env,{to:'client@example.test\r\nBcc: other@example.test',subject:'Test',text:'Test'}),/invalide/);
console.log('PASS: SMTP encrypted transport, multiline responses, authentication, mail envelope, UTF-8 MIME, rejection without delivery, header injection validation and connection cleanup. No external e-mails.');
