name = "mimflo-members"
main = "index.ts"
compatibility_date = "2026-05-22"
workers_dev = false
preview_urls = false

[triggers]
crons = ["0 3 * * *"]

[vars]
ALLOWED_ORIGIN = "https://renolix.github.io"

[[d1_databases]]
binding = "DB"
database_name = "mimflo-members"
database_id = "5ad3feca-1fc6-4a9f-acd8-d99373f018af"
migrations_dir = "migrations"
