ALTER TABLE articles ADD COLUMN images TEXT NOT NULL DEFAULT '[]';
ALTER TABLE requests ADD COLUMN customer TEXT NOT NULL DEFAULT '{}';
CREATE TABLE media (id TEXT PRIMARY KEY, content BLOB NOT NULL, mime TEXT NOT NULL, name TEXT NOT NULL, created_by TEXT NOT NULL REFERENCES users(id), created_at INTEGER NOT NULL);
CREATE TABLE categories (name TEXT PRIMARY KEY COLLATE NOCASE);
INSERT OR IGNORE INTO categories SELECT DISTINCT category FROM articles;
INSERT OR IGNORE INTO settings VALUES ('paypal_email','');
