'use client';
import {readingDuration} from './reading-duration';
import {useState} from 'react';
import {BookOpen,Plus,ArrowLeft,ArrowRight,ImagePlus,Upload,Trash2,Pencil,Search,Check} from 'lucide-react';
import {plans,categories} from './content';
import {articleImage} from './article-media';
import {uploadImage} from './image-upload';
import {Button} from '@/components/ui/button';
const paidPacks=['sprint','intensif','performance'];
const packList=[{id:'library',name:'Bibliothèque générale',days:0},{id:'trial',name:'Offre gratuite',days:2}];
const belongs=(a:any,pack:string)=>pack==='library'?a.packs.some((p:string)=>paidPacks.includes(p)):a.packs.includes(pack);
const blank=()=>({id:'',title:'',category:'Société',level:'B1',image:'environment.webp',imageUrl:'',intro:'',body:'',vocabulary:'',grammarText:'',published:false,packs:[] as string[],images:[] as any[]});
export default function AdminArticles({data,act,busy}:{data:any;act:(b:any)=>Promise<boolean>;busy:boolean}){
 const [screen,setScreen]=useState('home'),[pack,setPack]=useState(''),[editor,setEditor]=useState(blank()),[search,setSearch]=useState(''),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 const topics=[...new Set<string>([...categories.slice(1),...data.categories,...data.articles.map((a:any)=>a.category)])].sort((a,b)=>a.localeCompare(b,'fr'));
 const duration=readingDuration(editor.body);
 const packInfo=packList.find(p=>p.id===pack);
 const items=data.articles.filter((a:any)=>(pack==='unassigned'?!a.packs.length:belongs(a,pack))&&a.title.toLowerCase().includes(search.toLowerCase()));
 function openArticle(a?:any){setEditor(a?{...a,images:a.images||[],grammarText:(a.grammar||[]).map((note:any)=>[note.title,note.explanation,note.example].join(' | ')).join('\n'),body:a.paragraphs.join('\n\n'),vocabulary:a.words.map((w:string[])=>w.join(' | ')).join('\n')}:{...blank(),packs:pack==='trial'?['trial']:pack==='unassigned'?[]:paidPacks});setError('');setScreen('editor');}
 return <section className="content-manager"><div className="admin-section-title"><div><span className="eyebrow">VOTRE BIBLIOTHÈQUE</span><h1>{screen==='home'?'Articles & abonnements':screen==='packs'?'Mes bibliothèques':screen==='list'?(packInfo?.name||'Articles non affectés'):editor.id?'Modifier l’article':'Ajouter un nouvel article'}</h1><p>{screen==='home'?'Organisez vos contenus et préparez les lectures de vos clients.':screen==='packs'?'La bibliothèque des packs et la lecture de l’essai gratuit sont séparées.':screen==='list'?'Cliquez sur un article pour le modifier.':'Votre texte, vos images et sa publication dans la bibliothèque.'}</p></div>{screen!=='home'&&<button className="admin-back" onClick={()=>setScreen(screen==='editor'?(pack?'list':'home'):screen==='list'?'packs':'home')}><ArrowLeft size={17}/>Retour</button>}</div>
 {screen==='home'&&<div className="admin-launch-grid"><button className="admin-launch-card" onClick={()=>setScreen('packs')}><span className="admin-icon sage"><BookOpen/></span><h2>Mes bibliothèques</h2><p>Une bibliothèque commune aux trois packs et une offre gratuite indépendante.</p><span className="admin-launch-link">Gérer mes contenus <ArrowRight size={18}/></span></button><button className="admin-launch-card pink" onClick={()=>{setPack('');openArticle()}}><span className="admin-icon"><Plus/></span><h2>Ajouter un nouvel article</h2><p>Créez une lecture et ajoutez-la à la bibliothèque générale.</p><span className="admin-launch-link">Créer un article <ArrowRight size={18}/></span></button></div>}
 {screen==='packs'&&<><div className="admin-pack-grid">{packList.map((p,i)=><button key={p.id} className={'admin-pack-tile tone-'+i} onClick={()=>{setPack(p.id);setSearch('');setScreen('list')}}><span className="admin-icon"><BookOpen/></span><h2>{p.name}</h2><span className="pack-duration">{p.id==='trial'?'48 heures':'Packs 5, 10 et 15 jours'}</span><p>{data.articles.filter((a:any)=>belongs(a,p.id)).length} article(s)</p><span className="admin-launch-link">Ouvrir la bibliothèque <ArrowRight size={16}/></span></button>)}</div><button className="text-link" onClick={()=>{setPack('unassigned');setSearch('');setScreen('list')}}>Voir les articles non affectés ({data.articles.filter((a:any)=>!a.packs.length).length})</button></>}
 {screen==='list'&&<><div className="admin-toolbar"><label className="admin-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher un article" aria-label="Rechercher un article"/></label><Button className="btn" onClick={()=>openArticle()}><Plus size={17}/>Nouvel article</Button></div><div className="admin-article-grid">{items.map((a:any)=><button key={a.id} className="admin-article-card" onClick={()=>openArticle(a)}><img src={articleImage(a)} alt="" loading="lazy" decoding="async"/><div><span className={'status-tag '+(a.published?'published':'draft')}>{a.published?'Publié':'Brouillon'}</span><h3>{a.title}</h3><p>{a.category} · {a.level} · {a.minutes} min</p><span className="admin-launch-link"><Pencil size={14}/>Modifier l’article</span></div></button>)}</div>{!items.length&&<div className="admin-empty"><BookOpen/><h2>{search?'Aucun résultat':'Cette bibliothèque attend ses premières lectures'}</h2><p>{search?'Essayez un autre titre.':'Ajoutez un article pour construire votre programme.'}</p>{!search&&<Button className="btn" onClick={()=>openArticle()}>Ajouter un article</Button>}</div>}</>}
 {screen==='editor'&&<form className="article-editor" onSubmit={async e=>{e.preventDefault();setError('');if(await act({action:'article',article:{...editor,minutes:duration.minutes,grammar:editor.grammarText.split('\n').filter(Boolean).map(line=>{const [title,explanation,example]=line.split('|').map(value=>value.trim());return {title,explanation,example}}),paragraphs:editor.body.split(/\n\s*\n/).filter(Boolean),words:editor.vocabulary.split('\n').filter(Boolean).map(line=>line.split('|').map(x=>x.trim()))}})){const next=editor.packs.some(p=>paidPacks.includes(p))?'library':editor.packs.includes('trial')?'trial':'unassigned';setPack(next);setScreen('list');setSearch('')}}}>
 <div className="editor-main"><section className="card form-stack"><h2>Le contenu de votre lecture</h2><label className="field">Titre<input required maxLength={160} value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})} placeholder="Donnez un titre à votre article"/></label><div className="field-row"><label className="field">Thématique<input required maxLength={80} list="mimflo-topics" value={editor.category} onChange={e=>setEditor({...editor,category:e.target.value})}/><datalist id="mimflo-topics">{topics.map(c=><option key={c} value={c}/>)}</datalist><small>Choisissez une thématique ou écrivez-en une nouvelle. Elle sera ajoutée après sauvegarde.</small></label><label className="field">Niveau<select value={editor.level} onChange={e=>setEditor({...editor,level:e.target.value})}>{['A1','A2','B1','B2','B2/C1','C1','C2'].map(c=><option key={c}>{c}</option>)}</select></label></div><label className="field">Introduction<textarea rows={3} maxLength={1200} value={editor.intro} onChange={e=>setEditor({...editor,intro:e.target.value})} placeholder="Quelques mots pour présenter la lecture"/></label><label className="field">Texte de lecture<textarea required rows={13} value={editor.body} onChange={e=>setEditor({...editor,body:e.target.value})} placeholder="Écrivez votre article. Séparez les paragraphes par une ligne vide."/></label><label className="field">Vocabulaire<textarea rows={4} value={editor.vocabulary} onChange={e=>setEditor({...editor,vocabulary:e.target.value})} placeholder="Un mot | sa définition, par ligne"/></label><label className="field">Grammaire<textarea rows={5} value={editor.grammarText} onChange={event=>setEditor({...editor,grammarText:event.target.value})} placeholder="Un point par ligne : titre | explication | exemple"/><small>Ces fiches apparaissent après le texte, dans l’entraînement.</small></label></section>
 <section className="card"><div className="admin-card-title"><div><h2>Images de l’article</h2><p>Ajoutez des photos depuis votre ordinateur ou votre téléphone.</p></div><ImagePlus/></div><label className={'image-upload '+(uploading?'uploading':'')}><Upload/><strong>{uploading?'Téléversement en cours…':'Sélectionner des images'}</strong><span>JPEG, PNG, WebP · 8 images maximum · images optimisées automatiquement</span><input type="file" accept="image/*" multiple disabled={uploading||editor.images.length>=8} onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(files.length+editor.images.length>8){setError('Vous pouvez ajouter 8 images maximum.');return;}setUploading(true);setError('');try{for(const file of files){const media=await uploadImage(file);setEditor(current=>({...current,...(current.images.length===0?{image:'media:'+media.id,imageUrl:media.url}:{}),images:[...current.images,{id:media.id,url:media.url,caption:'',afterParagraph:-1}]}));}}catch(e:any){setError(e.message);}finally{setUploading(false);}}}/></label><div className="editor-images">{editor.images.map((m:any,i:number)=><div className="editor-image" key={m.id}><img src={m.url} alt={m.caption||'Image téléversée'}/><div><label className="field">Légende<input value={m.caption} maxLength={200} onChange={e=>setEditor({...editor,images:editor.images.map((x:any,j:number)=>j===i?{...x,caption:e.target.value}:x)})}/></label><label className="field">Emplacement<select value={m.afterParagraph} onChange={e=>setEditor({...editor,images:editor.images.map((x:any,j:number)=>j===i?{...x,afterParagraph:Number(e.target.value)}:x)})}><option value={-1}>Avant le texte</option>{editor.body.split(/\n\s*\n/).filter(Boolean).map((_,j)=><option value={j} key={j}>Après le paragraphe {j+1}</option>)}</select></label><div className="image-actions"><button type="button" className="text-link" onClick={()=>setEditor({...editor,image:'media:'+m.id,imageUrl:m.url})}>{editor.image==='media:'+m.id?<><Check size={14}/>Couverture</>:'Utiliser en couverture'}</button><button type="button" className="icon-delete" aria-label={'Retirer l’image '+(i+1)} onClick={()=>setEditor({...editor,images:editor.images.filter((_:any,j:number)=>j!==i),...(editor.image==='media:'+m.id?{image:'environment.webp',imageUrl:''}:{})})}><Trash2 size={16}/></button></div></div></div>)}</div></section></div>
 <aside className="editor-settings"><section className="card form-stack"><h2>Publication & accès</h2><div className="field"><span>Durée de lecture estimée</span><output aria-live="polite" className="reading-duration-output">{duration.words?`${duration.minutes} min · ${duration.words} mots`:'Ajoutez votre texte'}</output><small>Calculée automatiquement à partir du texte, pour une lecture à voix haute.</small></div><fieldset><legend>Disponible dans</legend>{packList.map(p=><label className="check-label" key={p.id}><input type="checkbox" checked={p.id==='library'?editor.packs.some(x=>paidPacks.includes(x)):editor.packs.includes(p.id)} onChange={e=>{const affected=p.id==='library'?paidPacks:[p.id];setEditor({...editor,packs:e.target.checked?[...new Set([...editor.packs,...affected])]:editor.packs.filter(x=>!affected.includes(x))})}}/>{p.name}</label>)}</fieldset><label className="check-label"><input type="checkbox" checked={!!editor.published} onChange={e=>setEditor({...editor,published:e.target.checked})}/>Publier cet article</label><p className="muted small">Un brouillon reste privé. Les trois packs partagent tous les articles publiés dans la bibliothèque générale, avec un nouveau choix toutes les 24 heures. L’essai gratuit garde son article à part.</p><Button className="btn" disabled={busy||uploading} type="submit">{busy?'Sauvegarde…':editor.id?'Sauvegarder les modifications':'Sauvegarder l’article'}</Button>{error&&<p className="notice" role="alert">{error}</p>}</section></aside></form>}
 </section>;
}
