'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ArrowRight,Check,GraduationCap,Headphones,Mic,RotateCcw,Square,X} from 'lucide-react';
import {memberRequest,memberPlacementAudioRequest} from './member-api';
import {audioToWav} from './audio-analysis';
import {getRecording,saveRecording} from './recording-store';
import {useArticleListening} from './use-article-listening';
import AnalysisLoadingOverlay from './analysis-loading-overlay';
import './language-placement.css';

export default function LanguagePlacement({disabled=false}:{disabled?:boolean}){
 const [open,setOpen]=useState(false),[data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;const load=()=>{memberRequest('/placement').then(value=>{if(active)setData(value)}).catch(()=>{})};load();window.addEventListener('mimflo-placement-updated',load);return()=>{active=false;window.removeEventListener('mimflo-placement-updated',load)}},[]);
 async function show(){if(disabled)return;setError('');try{const value=await memberRequest('/placement');setData(value);setOpen(true)}catch(e:any){setError(e.message)}}
 return <section className="language-placement-entry"><div className="placement-entry-title"><GraduationCap size={23}/><div><strong>{data?.latest?.result?.level?'Votre niveau estimé : '+data.latest.result.level:'Quel est mon niveau de français ?'}</strong><p>Questions de langue et expression libre · estimation A1 à C2</p></div></div><button className="placement-entry-button" disabled={disabled} onClick={show}>{data?.pending?'Reprendre mon test':data?.latest?'Voir mon test de niveau':'Estimer mon niveau'}<ArrowRight size={16}/></button>{data?.latest&&<small>Estimation indicative des compétences testées.</small>}{error&&<p role="status" className="notice">{error}</p>}{open&&data&&<PlacementDialog data={data} onClose={()=>setOpen(false)} onResult={result=>{setData((current:any)=>({...current,latest:{result}}));window.dispatchEvent(new Event('mimflo-placement-updated'));}}/>}</section>;
}
function PlacementDialog({data,onClose,onResult}:{data:any;onClose:()=>void;onResult:(result:any)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),titleId=useId(),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),started=useRef(0),mounted=useRef(true);
 const [test,setTest]=useState<any>(null),[answers,setAnswers]=useState<Record<string,number>>({}),[step,setStep]=useState(0),[stage,setStage]=useState<'intro'|'questions'|'oral'|'result'>(data.latest&&!data.pending?'result':'intro');
 const [result,setResult]=useState<any>(data.latest?.result),[busy,setBusy]=useState(false),[error,setError]=useState(''),[recording,setRecording]=useState(false),[starting,setStarting]=useState(false),[seconds,setSeconds]=useState(0),[blob,setBlob]=useState<Blob|null>(null),[audioUrl,setAudioUrl]=useState(''),[consent,setConsent]=useState(false);
 const listening=useArticleListening(data.prompt,setError),maxSeconds=data.maxSeconds||600;
 useEffect(()=>{mounted.current=true;const el=dialog.current;if(!el)return;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';el.showModal();return()=>{mounted.current=false;el.close();document.body.style.overflow=overflow;const rec=recorder.current;if(rec?.state==='recording')rec.stop();stream.current?.getTracks().forEach(t=>t.stop())}},[]);
 useEffect(()=>{if(!blob){setAudioUrl('');return;}const url=URL.createObjectURL(blob);setAudioUrl(url);return()=>URL.revokeObjectURL(url)},[blob]);
 useEffect(()=>{if(!recording)return;const timer=setInterval(()=>{const elapsed=Math.floor((Date.now()-started.current)/1000);setSeconds(Math.min(elapsed,maxSeconds));if(elapsed>=maxSeconds)stop()},250);return()=>clearInterval(timer)},[recording,maxSeconds]);
 function acceptResult(value:any){setResult(value);onResult(value);setStage('result')}
 async function recover(id:string){
  const deadline=Date.now()+300000;
  while(mounted.current&&Date.now()<deadline){
   const state=await memberRequest('/placement/'+id);
   if(state.status==='completed'&&state.result){acceptResult(state.result);return true;}
   if(state.status!=='processing')return false;
   await new Promise(resolve=>setTimeout(resolve,2500));
  }
  return false;
 }
 async function begin(){setBusy(true);setError('');try{const value=await memberRequest('/placement/start',{});setTest(value);let restored=value.answers||{};try{restored=JSON.parse(sessionStorage.getItem('mimflo-placement-answers:'+value.id)||'null')||restored}catch{}setAnswers(restored);if(value.quiz){setStage('oral');const audio=await getRecording('placement:'+value.id).catch(()=>null);setBlob(audio);if(value.status==='processing'&&!await recover(value.id))setError('Votre enregistrement est conservé. Réessayez son analyse.');}else{const unanswered=data.questions.findIndex((q:any)=>restored[q.id]===undefined);setStep(Math.max(0,unanswered));setStage('questions')}}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function next(){if(step<data.questions.length-1){setStep(step+1);return;}setBusy(true);setError('');try{await memberRequest('/placement/answers',{id:test.id,answers});setStage('oral')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function record(){if(recording||busy||starting)return;listening.stop();setError('');setStarting(true);try{const media=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;const rec=new MediaRecorder(media),chunks:BlobPart[]=[];recorder.current=rec;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{media.getTracks().forEach(t=>t.stop());if(!mounted.current)return;const audio=new Blob(chunks,{type:rec.mimeType});setBlob(audio);setRecording(false);void saveRecording('placement:'+test.id,audio).catch(()=>setError('L’audio reste disponible ici, mais son stockage local est indisponible.'));};started.current=Date.now();setSeconds(0);rec.start();setRecording(true);}catch{setError('Autorisez le microphone et vérifiez le périphérique choisi dans votre navigateur.')}finally{if(mounted.current)setStarting(false)}}
 function stop(){if(recorder.current?.state==='recording'){setRecording(false);recorder.current.stop()}}
 async function analyse(){if(!blob||!consent||busy)return;setBusy(true);setError('');listening.stop();try{const audio=await audioToWav(blob,maxSeconds),value=await memberPlacementAudioRequest(test.id,audio);if(!mounted.current)return;acceptResult(value.result)}catch(e:any){if(mounted.current){try{if(await recover(test.id))return;}catch{}if(mounted.current)setError(e.message)}}finally{if(mounted.current)setBusy(false)}}
 useEffect(()=>{if(test&&stage==='questions')try{sessionStorage.setItem('mimflo-placement-answers:'+test.id,JSON.stringify(answers))}catch{}},[answers,test,stage]);
 const question=data.questions[step],answer=question&&answers[question.id],progress=stage==='questions'?Math.round(step/data.questions.length*100):stage==='oral'?80:100;
 function close(){if(busy||recording||starting)return;listening.stop();onClose()}
 return createPortal(<dialog className="placement-dialog" ref={dialog} aria-labelledby={titleId} onCancel={e=>{e.preventDefault();close()}}><header><div><span className="section-overline">VOTRE FRANÇAIS, AUJOURD’HUI</span><h2 id={titleId}>Mon test de niveau</h2></div><button aria-label="Fermer le test de niveau" onClick={close} disabled={busy||recording||starting}><X size={20}/></button></header><div className="placement-dialog-body">
  {stage==='intro'&&<><div className="placement-intro-icon"><GraduationCap size={38}/></div><h3>Faites le point sur votre français.</h3><p>Répondez à 24 questions de grammaire, de vocabulaire et de compréhension, puis exprimez-vous avec vos propres mots.</p><ul><li>Les six niveaux sont considérés : A1, A2, B1, B2, C1 et C2.</li><li>Aucune limite de 30 secondes : vous disposez de 10 minutes pour votre réponse orale.</li><li>Un test inclus dans l’essai offert. Les nouveaux tests des abonnés dépendent du quota gratuit disponible.</li></ul><p className="placement-disclaimer">Ce test propose une estimation indicative. Il n’est pas étalonné ni certifié CECRL et ne mesure pas l’accent ou la fluidité acoustique.</p><button className="btn" onClick={begin} disabled={busy||!data.enabled}>{busy?'Ouverture…':data.pending?'Reprendre mon test':'Commencer mon test'}<ArrowRight size={16}/></button>{!data.enabled&&<p>Le test est temporairement indisponible.</p>}</>}
  {(stage==='questions'||stage==='oral')&&<><div className="placement-progress-label"><span>{stage==='questions'?'01 · Questions de langue':'02 · Expression libre'}</span><strong>{stage==='questions'?(step+1)+' / '+data.questions.length:'À vous de parler'}</strong></div><div className="placement-progress"><i style={{width:progress+'%'}}/></div></>}
  {stage==='questions'&&question&&<><span className="placement-skill">{question.skill}</span><h3 className="placement-question">{question.text}</h3><div className="placement-options" role="radiogroup" aria-label={question.text}>{question.choices.map((choice:string,index:number)=><button key={index} role="radio" aria-checked={answer===index} onClick={()=>setAnswers(current=>({...current,[question.id]:index}))} disabled={busy}><i>{String.fromCharCode(65+index)}</i><span>{choice}</span>{answer===index&&<Check size={18}/>}</button>)}</div><div className="placement-question-actions"><button className="text-link" onClick={()=>setStep(step-1)} disabled={!step||busy}>Précédent</button><button className="btn" onClick={next} disabled={answer===undefined||busy}>{busy?'Sauvegarde…':step===data.questions.length-1?'Passer à l’oral':'Question suivante'}<ArrowRight size={16}/></button></div></>}
  {stage==='oral'&&<><h3>Exprimez-vous librement.</h3><p className="placement-prompt">{data.prompt}</p><button className="text-link" onClick={listening.toggle} disabled={recording||busy}>{listening.playing?<Square size={16}/>:<Headphones size={16}/>} {listening.playing?'Arrêter la consigne':'Écouter la consigne'}</button><p className="muted small">Prenez le temps de raconter et de développer vos idées. Une réponse très courte ne suffit pas à estimer un niveau. Durée maximale : 10 minutes.</p>{audioUrl&&<audio src={audioUrl} controls preload="metadata" aria-label="Écouter mon expression orale"/>}<div className="placement-record-controls"><span>{recording?'Enregistrement en cours':'Votre réponse orale'} <b>{Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')}</b></span><button className="btn" onClick={recording?stop:record} disabled={busy||starting}>{recording?<Square size={17}/>:blob?<RotateCcw size={17}/>:<Mic size={17}/>} {recording?'Arrêter':starting?'Microphone…':blob?'Refaire':'Enregistrer'}</button></div><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={busy||recording}/>J’autorise l’analyse de mon expression orale. La transcription et mon résultat sont sauvegardés dans mon espace ; l’audio reste sur cet appareil.</label><button className="btn sage" onClick={analyse} disabled={!blob||!consent||recording||busy}>Analyser mon test de niveau<ArrowRight size={16}/></button></>}
  {stage==='result'&&result&&<><div className="placement-result-level"><span>NIVEAU INDICATIF DES COMPÉTENCES TESTÉES</span><strong>{result.level||'À préciser'}</strong><p>{result.level?'Votre résultat combine les questions de langue et votre expression personnelle.':'Votre réponse ne permet pas encore de proposer un niveau.'}</p></div><div className="placement-results-grid"><div><span>Questions de langue</span><strong>{result.quiz?.level}</strong><p>{result.quiz?.correct} bonnes réponses sur {result.quiz?.total}</p>{result.quiz?.startingLevelUnconfirmed&&<small>Les bases A1 restent à confirmer.</small>}</div><div><span>Expression personnelle</span><strong>{result.oral?.level==='insufficient'?'À préciser':result.oral?.level}</strong><p>{result.oral?.reason}</p></div></div>{result.oral?.strengths?.length>0&&<div className="placement-feedback positive"><h4>Vos points forts</h4><ul>{result.oral.strengths.map((text:string,i:number)=><li key={i}>{text}</li>)}</ul></div>}{result.oral?.improvements?.length>0&&<div className="placement-feedback"><h4>Pour aller plus loin</h4><ul>{result.oral.improvements.map((text:string,i:number)=><li key={i}>{text}</li>)}</ul></div>}<details className="placement-evidence"><summary>Voir les éléments de mon évaluation</summary>{result.quiz?.levels?.map((row:any)=><p key={row.level}><strong>{row.level}</strong> · {row.correct}/{row.total} réponses correctes</p>)}{result.oral?.evidence?.map((entry:any,i:number)=><blockquote key={i}>« {entry.quote} »<p>{entry.observation}</p></blockquote>)}<h4>Ma transcription</h4><p>{result.transcript}</p></details><p className="placement-disclaimer">{result.limitations}</p><button className="btn secondary" onClick={begin} disabled={busy}>Refaire un test</button></>}
  {error&&<p className="notice" role="status">{error}</p>}
 </div>{busy&&stage==='oral'&&<AnalysisLoadingOverlay canCancel={false} onCancel={()=>{}}/>}</dialog>,document.body);
}
