'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ArrowRight,Target,Headphones,Mic,RotateCcw,Square,X} from 'lucide-react';
import {memberRequest,memberPlacementAudioRequest} from './member-api';
import {audioToWav} from './audio-analysis';
import {getRecording,saveRecording} from './recording-store';
import {useArticleListening} from './use-article-listening';
import AnalysisLoadingOverlay from './analysis-loading-overlay';
import './language-placement.css';

export default function LanguagePlacement({articleId,articleTitle,disabled=false,onOpen}:{articleId:string;articleTitle:string;disabled?:boolean;onOpen?:()=>void}){
 const [open,setOpen]=useState(false),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const endpoint='/placement?articleId='+encodeURIComponent(articleId);
 useEffect(()=>{let active=true;setData(null);const load=()=>{memberRequest(endpoint).then(value=>{if(active)setData(value)}).catch(()=>{})};load();window.addEventListener('mimflo-placement-updated',load);return()=>{active=false;window.removeEventListener('mimflo-placement-updated',load)}},[endpoint]);
 async function show(){if(disabled||loading)return;setLoading(true);setError('');onOpen?.();try{const value=await memberRequest(endpoint);setData(value);setOpen(true)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 return <><section className="oral-challenge-banner" aria-label="Défi final"><span className="oral-challenge-icon"><Target size={28}/></span><div className="oral-challenge-copy"><h2>Défi final</h2><p>Votre avis sur le sujet de l’article, en 4 minutes maximum.</p>{data?.latest?.result?.level&&<span className="oral-challenge-level">Votre niveau oral estimé : <strong>{data.latest.result.level}</strong></span>}</div><button onClick={show} disabled={disabled||loading}><Mic size={16}/>{loading?'Ouverture…':data?.pending?'Reprendre mon défi':data?.latest?'Voir mon résultat':'Commencer le défi'}<ArrowRight size={16}/></button></section>{error&&<p className="notice" role="status">{error}</p>}{open&&data&&<PlacementDialog key={articleId} data={data} articleId={articleId} articleTitle={articleTitle} onClose={()=>setOpen(false)} onResult={result=>{setData((current:any)=>({...current,pending:null,latest:{result}}));window.dispatchEvent(new Event('mimflo-placement-updated'));}}/>}</>;
}
function PlacementDialog({data,articleId,articleTitle,onClose,onResult}:{data:any;articleId:string;articleTitle:string;onClose:()=>void;onResult:(result:any)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),titleId=useId(),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),started=useRef(0),mounted=useRef(true);
 const [test,setTest]=useState<any>(null),[stage,setStage]=useState<'intro'|'oral'|'result'>(data.latest&&!data.pending?'result':'intro');
 const [result,setResult]=useState<any>(data.latest?.result),[busy,setBusy]=useState(false),[error,setError]=useState(''),[recording,setRecording]=useState(false),[starting,setStarting]=useState(false),[seconds,setSeconds]=useState(0),[blob,setBlob]=useState<Blob|null>(null),[audioUrl,setAudioUrl]=useState(''),[consent,setConsent]=useState(false);
 const topic=test?.topic||data.topic,listening=useArticleListening(topic?.prompt||'',setError),maxSeconds=240;
 const player=useRef<HTMLAudioElement|null>(null),hardStop=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [capturing,setCapturing]=useState(false);
 useEffect(()=>{mounted.current=true;const el=dialog.current;if(!el)return;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';el.showModal();return()=>{mounted.current=false;if(hardStop.current)clearTimeout(hardStop.current);el.close();document.body.style.overflow=overflow;const rec=recorder.current;if(rec?.state==='recording')rec.stop();stream.current?.getTracks().forEach(t=>t.stop())}},[]);
 useEffect(()=>{if(!blob){setAudioUrl('');return;}const url=URL.createObjectURL(blob);setAudioUrl(url);return()=>URL.revokeObjectURL(url)},[blob]);
 useEffect(()=>{if(!recording)return;const timer=setInterval(()=>{const elapsed=Math.floor((Date.now()-started.current)/1000);setSeconds(Math.min(elapsed,maxSeconds));if(elapsed>=maxSeconds)stop()},250);return()=>clearInterval(timer)},[recording,maxSeconds]);
 function acceptResult(value:any){if(!value)throw Error('Votre résultat est indisponible. Réessayez avec cet enregistrement.');setResult(value);onResult(value);setStage('result')}
 async function recover(id:string){
  const deadline=Date.now()+300000;
  while(mounted.current&&Date.now()<deadline){
   const state=await memberRequest('/placement/'+id);
   if(state.status==='completed'&&state.result){acceptResult(state.result);return true;}
   if(state.status!=='processing')return false;
   await new Promise(resolve=>setTimeout(resolve,2500));
  }
  return false;
 }
 async function begin(){setBusy(true);setError('');try{const value=await memberRequest('/placement/start',{articleId});if(!mounted.current)return;setTest(value);setStage('oral');setConsent(false);setSeconds(0);const audio=await getRecording('placement:'+value.id).catch(()=>null);if(!mounted.current)return;setBlob(audio);if(value.status==='processing'&&!await recover(value.id))setError('Votre enregistrement est conservé. Réessayez son analyse.');}catch(e:any){if(mounted.current)setError(e.message)}finally{if(mounted.current)setBusy(false)}}
 async function record(){if(recording||busy||starting||capturing)return;listening.stop();player.current?.pause();setError('');setStarting(true);try{const media=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;const rec=new MediaRecorder(media),chunks:BlobPart[]=[];recorder.current=rec;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onerror=()=>{rec.onstop=null;if(hardStop.current)clearTimeout(hardStop.current);media.getTracks().forEach(t=>t.stop());if(mounted.current){setRecording(false);setCapturing(false);setError('L’enregistrement a été interrompu. Vérifiez votre microphone et réessayez.')}};rec.onstop=()=>{if(hardStop.current)clearTimeout(hardStop.current);media.getTracks().forEach(t=>t.stop());if(!mounted.current)return;const audio=new Blob(chunks,{type:rec.mimeType});setBlob(audio);setSeconds(Math.min(maxSeconds,Math.floor((Date.now()-started.current)/1000)));setRecording(false);setCapturing(false);void saveRecording('placement:'+test.id,audio).catch(()=>setError('L’audio reste disponible ici, mais son stockage local est indisponible.'));};started.current=Date.now();setSeconds(0);rec.start();setRecording(true);hardStop.current=setTimeout(stop,maxSeconds*1000);}catch{setError('Autorisez le microphone et vérifiez le périphérique choisi dans votre navigateur.')}finally{if(mounted.current)setStarting(false)}}
 function stop(){if(recorder.current?.state==='recording'){setCapturing(true);setRecording(false);recorder.current.stop()}}
 async function analyse(){if(!blob||!consent||busy||recording||starting||capturing)return;setBusy(true);setError('');listening.stop();player.current?.pause();try{const audio=await audioToWav(blob,maxSeconds),value=await memberPlacementAudioRequest(test.id,audio);if(!mounted.current)return;acceptResult(value.result)}catch(e:any){if(mounted.current){try{if(await recover(test.id))return;}catch{}if(mounted.current)setError(e.message)}}finally{if(mounted.current)setBusy(false)}}
 function close(){if(busy||recording||starting||capturing)return;listening.stop();onClose()}
 return createPortal(<dialog className="placement-dialog" ref={dialog} aria-labelledby={titleId} onCancel={e=>{e.preventDefault();close()}}><header><div><span className="section-overline">DÉFI FINAL · EXPRESSION ORALE</span><h2 id={titleId}>À vous de prendre la parole</h2></div><button aria-label="Fermer le défi final" onClick={close} disabled={busy||recording||starting||capturing}><X size={20}/></button></header><div className="placement-dialog-body">
  {stage==='intro'&&<><div className="placement-intro-icon"><Mic size={38}/></div><h3>Votre voix, vos idées.</h3><p>Parlez librement du sujet de l’article. Votre réponse permet d’estimer votre niveau d’expression orale, de A1 à C2.</p><div className="placement-article-topic"><span>LE SUJET DE VOTRE DÉFI</span><strong>{topic?.title||articleTitle}</strong></div><ul><li>Présentez le sujet avec vos propres mots.</li><li>Donnez votre avis et développez-le avec des exemples.</li><li>Enregistrez jusqu’à 4 minutes ; vous pouvez vous arrêter avant.</li></ul><p className="placement-disclaimer">Le niveau est une estimation indicative à partir de votre réponse personnelle, et non une certification CECRL.</p><button className="btn" onClick={begin} disabled={busy||!data.enabled}>{busy?'Ouverture…':data.pending?'Reprendre mon enregistrement':'Préparer mon enregistrement'}<ArrowRight size={16}/></button>{!data.enabled&&<p>Le défi est temporairement indisponible. Vérifiez votre accès à cet article et réessayez.</p>}</>}
  {stage==='oral'&&<><div className="placement-article-topic"><span>VOTRE SUJET</span><strong>{topic?.title||articleTitle}</strong></div><p className="placement-prompt">{topic?.prompt}</p><button className="text-link" onClick={listening.toggle} disabled={recording||busy||starting||capturing}>{listening.playing?<Square size={16}/>:<Headphones size={16}/>} {listening.playing?'Arrêter la consigne':'Écouter la consigne'}</button><p className="muted small">Prenez le temps de raconter et de développer vos idées. Une réponse très courte ne suffit pas à estimer un niveau. L’enregistrement s’arrête automatiquement à 4 minutes.</p>{audioUrl&&!recording&&!starting&&<audio ref={player} onLoadedMetadata={e=>{if(Number.isFinite(e.currentTarget.duration))setSeconds(Math.min(maxSeconds,Math.round(e.currentTarget.duration)))}} src={audioUrl} controls preload="metadata" aria-label="Écouter mon expression orale"/>}<div className="placement-record-controls"><span>{recording?'Enregistrement en cours':'Votre réponse orale'} <b>{Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')} <small>/ 4:00</small></b></span><button className="btn" onClick={recording?stop:record} disabled={busy||starting||capturing}>{recording?<Square size={17}/>:blob?<RotateCcw size={17}/>:<Mic size={17}/>} {recording?'Arrêter':starting?'Microphone…':blob?'Refaire':'Enregistrer'}</button></div><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={busy||recording}/>J’autorise l’analyse de mon expression orale. La transcription et mon résultat sont sauvegardés dans mon espace ; l’audio reste sur cet appareil.</label><button className="btn sage" onClick={analyse} disabled={!blob||!consent||recording||busy||starting||capturing}>Obtenir mon niveau oral<ArrowRight size={16}/></button></>}
  {stage==='result'&&result&&<><div className="placement-result-level"><span>VOTRE NIVEAU ORAL ESTIMÉ</span><strong>{result.level||'À préciser'}</strong><p>{result.level?'Estimation fondée sur votre expression personnelle sur le sujet de l’article.':'Votre réponse ne permet pas encore de proposer un niveau.'}</p></div><div className="placement-article-topic"><span>VOTRE SUJET</span><strong>{result.articleTitle||articleTitle}</strong></div><div className="placement-feedback"><h4>Votre expression orale</h4><p>{result.oral?.reason}</p></div>{result.oral?.strengths?.length>0&&<div className="placement-feedback positive"><h4>Vos points forts</h4><ul>{result.oral.strengths.map((text:string,i:number)=><li key={i}>{text}</li>)}</ul></div>}{result.oral?.improvements?.length>0&&<div className="placement-feedback"><h4>Pour aller plus loin</h4><ul>{result.oral.improvements.map((text:string,i:number)=><li key={i}>{text}</li>)}</ul></div>}<details className="placement-evidence"><summary>Voir les éléments de mon évaluation</summary>{result.oral?.evidence?.map((entry:any,i:number)=><blockquote key={i}>« {entry.quote} »<p>{entry.observation}</p></blockquote>)}<h4>Ma transcription</h4><p>{result.transcript}</p></details><p className="placement-disclaimer">{result.limitations}</p><button className="btn secondary" onClick={begin} disabled={busy}>Refaire un défi</button></>}
  {error&&<p className="notice" role="status">{error}</p>}
 </div>{busy&&stage==='oral'&&<AnalysisLoadingOverlay canCancel={false} onCancel={()=>{}}/>}</dialog>,document.body);
}
