'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {memberRequest,setMemberToken} from './member-api';
import GoogleSignIn from './google-sign-in';
import PasswordStrength from './password-strength';
import {validPassword,passwordRequirements} from './password-rules';
import {plans} from './content';
export function AuthPanel({onComplete,intent=''}:{onComplete:(mode:'register'|'login')=>Promise<void>;intent?:string}){
 const [mode,setMode]=useState<'register'|'login'>('register'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[form,setForm]=useState({email:'',password:'',firstName:'',lastName:'',level:'B1',consent:false});
 const change=(k:string,v:any)=>setForm(f=>({...f,[k]:v}));
 return <form className="card form-stack" onSubmit={async e=>{e.preventDefault();if(mode==='register'&&!validPassword(form.password)){setError(passwordRequirements);return;}setBusy(true);setError('');try{const result=await memberRequest('/auth/'+mode,form);setMemberToken(result.token);await onComplete(mode);}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><h2>{mode==='register'?'Créer mon compte':'Se connecter'}</h2><p className="muted">{intent||'Inscrivez-vous pour choisir un pack ou profiter de votre unique essai gratuit.'}</p><div className="auth-tabs"><button type="button" className={mode==='register'?'selected':''} onClick={()=>{setMode('register');setError('')}}>Inscription</button><button type="button" className={mode==='login'?'selected':''} onClick={()=>{setMode('login');setError('')}}>Connexion</button></div>{mode==='register'&&<><div className="field-row"><label className="field">Prénom<Input required maxLength={60} value={form.firstName} onChange={e=>change('firstName',e.target.value)} autoComplete="given-name"/></label><label className="field">Nom<Input required maxLength={60} value={form.lastName} onChange={e=>change('lastName',e.target.value)} autoComplete="family-name"/></label></div><label className="field">Niveau de français<select value={form.level} onChange={e=>change('level',e.target.value)}>{['A1','A2','B1','B2','C1','C2'].map(v=><option key={v}>{v}</option>)}</select></label></>}<label className="field">E-mail<Input type="email" required maxLength={254} autoComplete="email" value={form.email} onChange={e=>change('email',e.target.value)}/></label><label className="field">Mot de passe<Input type="password" required minLength={mode==='register'?12:1} maxLength={128} autoComplete={mode==='register'?'new-password':'current-password'} value={form.password} onChange={e=>change('password',e.target.value)}/></label>{mode==='register'&&<PasswordStrength value={form.password}/>}{mode==='register'&&<label className="check-label"><input type="checkbox" checked={form.consent} onChange={e=>change('consent',e.target.checked)} required/><span>J’accepte les conditions d’utilisation et la politique de confidentialité. Pour limiter les essais multiples, une empreinte de mon adresse IP est conservée.</span></label>}<Button className="btn" type="submit" disabled={busy}>{busy?'Patientez…':mode==='register'?'Créer mon compte':'Se connecter'}</Button>{error&&<p className="notice" role="alert">{error}</p>}<GoogleSignIn mode={mode} consent={form.consent} level={form.level} onComplete={()=>onComplete(mode)}/></form>;
}
export function AccessGate({go,title='Votre bibliothèque est réservée aux membres.',description='Connectez-vous ou créez votre compte pour commencer votre essai gratuit ou choisir un abonnement.'}:{go:(v:string)=>void;title?:string;description?:string}){return <section className="card access-gate"><h2>{title}</h2><p>{description}</p><div className="actions"><Button className="btn" onClick={()=>go('inscription')}>S’inscrire / Se connecter</Button><Button className="btn secondary" onClick={()=>go('accueil')}>Retour à l’accueil</Button></div></section>}
export function MemberAccess({account,go,refresh}:{account:any;go:(v:string,a?:string)=>void;refresh:()=>Promise<any>}){const [busy,setBusy]=useState(false),[message,setMessage]=useState('');return <section className="card member-access"><h2>Mon abonnement et mes accès</h2>{!account.user.emailVerified&&<div className="notice"><p>{account.emailDeliveryEnabled?'Votre adresse e-mail doit être confirmée pour activer l’essai gratuit. Vérifiez votre boîte de réception et vos courriers indésirables.':'Votre adresse e-mail doit être confirmée par MimFlo avant l’essai gratuit. La vérification de votre compte est en attente.'}</p>{account.emailDeliveryEnabled&&<Button className="btn secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await memberRequest('/auth/resend',{});setMessage(r.verificationPending?'L’envoi automatique est indisponible. Contactez MimFlo.':'Le lien de vérification a été envoyé.');}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}}>Renvoyer le lien</Button>}</div>}<div className="access-list">{account.entitlements?.map((a:any)=><div className="card" key={a.id}><h3>{plans.find(p=>p.id===a.plan)?.name}</h3><p>Actif jusqu’au {new Date(a.ends_at).toLocaleString('fr-FR')}</p><Button className="btn" onClick={()=>go('bibliotheque')}>Ouvrir mes articles</Button></div>)}</div>{!account.entitlements?.length&&<p className="muted">L’accès à un pack est activé après vérification de votre paiement par MimFlo.</p>}{account.requests?.map((r:any)=><div className="notice" key={r.id}><p>{plans.find(p=>p.id===r.plan)?.name} — {r.status==='pending'?'Commande en attente de vérification':r.status==='approved'?'Paiement validé':'Demande refusée'}</p>{r.status==='pending'&&<Button className="btn secondary" onClick={()=>go('checkout',r.plan)}>Reprendre ma commande</Button>}</div>)}<div className="actions"><Button className="btn" onClick={()=>go('packs')}>Choisir un pack</Button>{!account.profile.trial_at&&<Button className="btn secondary" onClick={()=>go('essai')}>Mon unique essai gratuit</Button>}</div>{message&&<p className="notice" role="status">{message}</p>}</section>}
