'use client';
import {useEffect,useRef,useState} from 'react';
import {PanelLeft,X,User,BookOpen,BarChart3,NotebookPen,HelpCircle,Target,LogOut,ShieldCheck} from 'lucide-react';
export default function ProfileSidebar({profile,role,status,go,logout}:{profile:any;role:string;status:string;go:(view:string)=>void;logout:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[leaving,setLeaving]=useState(false),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(!open)return;const element=dialog.current;if(!element)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';element.showModal();return()=>{document.body.style.overflow=previous;if(element.open)element.close();};},[open]);
 function navigate(view:string){setOpen(false);go(view);}
 function content(){return <><div className="member-identity"><div className="avatar">{profile.first_name.slice(0,1)}{profile.last_name.slice(0,1)}</div><h2>{profile.first_name} {profile.last_name}</h2><p className="muted small">Membre depuis {new Date(profile.created_at).toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}<br/>Niveau : {profile.level}{profile.exam&&profile.exam!=='Aucun examen'&&<><br/>Objectif : {profile.exam}</>}</p><span className="pill">{status}</span></div><nav className="profile-menu" aria-label="Navigation de mon profil">{[[User,'profil','Mon profil'],[BookOpen,'parcours','Mes parcours'],[BarChart3,'progression','Mes progrès'],[NotebookPen,'notes','Mes notes'],[HelpCircle,'aide','Aide & FAQ'],[Target,'abonnement','Mon abonnement']].map(([Icon,view,label]:any)=><button type="button" key={view} onClick={()=>navigate(view)} aria-current={view==='profil'?'page':undefined}><Icon size={18}/><span>{label}</span></button>)}{['owner','admin'].includes(role)&&<button type="button" onClick={()=>navigate('admin')}><ShieldCheck size={18}/><span>Administration</span></button>}<button type="button" className="logout" disabled={leaving} onClick={async()=>{setLeaving(true);try{await logout();setOpen(false);}finally{setLeaving(false);}}}><LogOut size={18}/><span>{leaving?'Déconnexion…':'Déconnexion'}</span></button></nav></>;}
 return <><aside className="card member-sidebar">{content()}</aside><button type="button" className="profile-drawer-trigger" aria-label="Ouvrir le menu de mon profil" aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(true)}><PanelLeft size={20}/><span>Mon espace</span></button><dialog ref={dialog} className="profile-drawer" aria-labelledby="profile-drawer-title" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} onClick={e=>{if(e.target===dialog.current){const box=dialog.current!.getBoundingClientRect();if(e.clientX>box.right)setOpen(false);}}}>{open&&<><div className="profile-drawer-heading"><h2 id="profile-drawer-title">Mon espace</h2><button type="button" aria-label="Fermer le menu de mon profil" onClick={()=>setOpen(false)}><X size={22}/></button></div>{content()}</>}</dialog></>;
}
