'use client';
import {useEffect,useState} from 'react';
import {Sparkles,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {memberAudioRequest,memberRequest} from './member-api';
import {audioToWav} from './audio-analysis';
import {localPronunciation} from './local-pronunciation';
export function ReadingAnalysis({analysis}:{analysis:any}){return <section className="reading-ai-result" aria-label="Résultat de l’analyse de lecture"><h3>Votre analyse de lecture{analysis.passage?' · passage '+analysis.passage:''}</h3><div className="reading-ai-metrics"><div><strong>{analysis.score}/100</strong><span>Fidélité au passage</span></div><div><strong>{analysis.wordsPerMinute}</strong><span>Mots reconnus / minute</span></div></div><p>{analysis.missing} mots non reconnus · {analysis.different} mots différents · {analysis.added} ajouts</p>{analysis.differences?.length>0&&<details><summary>Voir les écarts repérés</summary><ul>{analysis.differences.map((d:any,i:number)=><li key={i}>{d.kind==='missing'?<>Non reconnu : <strong>{d.expected}</strong></>:d.kind==='added'?<>Ajout reconnu : <strong>{d.heard}</strong></>:<>Dans le texte : <strong>{d.expected}</strong> · reconnu : <strong>{d.heard}</strong></>}</li>)}</ul></details>}<ul>{analysis.tips?.map((tip:string)=><li key={tip}>{tip}</li>)}</ul><p className="muted small">{analysis.limitation}</p></section>}
export default function ReadingAiPanel({articleId,reference,blob,seconds,maxSeconds,saved,recording,passageIndex,onSaved,onBusy}:{articleId:string;reference:string;blob:Blob|null;seconds:number;maxSeconds:number;saved:boolean;recording:boolean;passageIndex:number;onSaved:(result:any)=>void|Promise<void>;onBusy:(busy:boolean)=>void}){
 const [enabled,setEnabled]=useState(true),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<any>(null),[job,setJob]=useState('');
 useEffect(()=>{let active=true;memberRequest('/analysis/status').then(d=>{if(active)setEnabled(d.enabled)}).catch(()=>{});return()=>{active=false}},[]);
 useEffect(()=>{setResult(null);setMessage('');setJob('');setConsent(false)},[blob]);
 async function analyse(){if(!blob||!consent)return;setBusy(true);onBusy(true);setMessage('');const key=job||crypto.randomUUID();setJob(key);try{const wav=await audioToWav(blob,maxSeconds);let data:any;try{const local=await localPronunciation(wav,reference,seconds,setMessage);const savedSession=await memberRequest('/account',{action:'session',articleId,seconds,transcript:local.transcript,analysis:local.analysis});data={...local,id:savedSession.id,ok:true};}catch(localError){setMessage('Analyse locale indisponible, tentative du service de secours…');data=await memberAudioRequest(key,articleId,wav,passageIndex);}setResult(data);await onSaved({...data,recordingBlob:blob});}catch(e:any){setMessage(e.message);if(!/encore en cours|prend plus de temps/.test(e.message))setJob('');}finally{setBusy(false);onBusy(false)}}
 return <section className="reading-ai-panel"><div className="reading-ai-heading"><Sparkles/><div><h3>Votre lecture, analysée localement</h3><p>Wav2Vec2/XLS-R fonctionne directement dans votre navigateur. Votre audio reste sur votre appareil et le modèle est téléchargé lors de la première analyse.</p></div></div>{enabled?<><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={busy||saved||recording}/>J’autorise l’analyse automatique de cette lecture. La transcription, le score et l’enregistrement sont sauvegardés dans mon espace.</label><Button className="btn sage" onClick={analyse} disabled={!blob||seconds<3||seconds>maxSeconds||!consent||busy||saved||recording}>{result?<Check/>:<Sparkles/>}{result?'Analyse sauvegardée':busy?'Analyse de votre lecture…':'Analyser et sauvegarder ma lecture'}</Button>{!blob&&<p className="muted small">Choisissez un passage puis enregistrez votre lecture pour commencer.</p>}</>:null}{message&&<p className="notice" role="status">{message}</p>}{result&&<><p><strong>Texte reconnu :</strong> {result.transcript}</p><ReadingAnalysis analysis={result.analysis}/></>}</section>
}
