'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {Activity,AlertCircle,Check,ChevronDown,Headphones,Lightbulb,RotateCcw,ShieldCheck,Square,Volume2,Sparkles} from 'lucide-react';
import {reportData,wordFeedback,type ReportWord} from './reading-report-data';
import './reading-report.css';
const decimal=(value:number)=>Number(value||0).toLocaleString('fr-FR',{maximumFractionDigits:1});
const isPhonetic=(analysis:any)=>analysis?.kind==='phonetic-experimental';
function ScoreRing({score,label}:{score:number|null;label:string}){
 const circumference=2*Math.PI*76;
 return <div className="report-score-ring" role="img" aria-label={score===null?'Score indisponible':`${label} : ${score} sur 100`}><svg viewBox="0 0 184 184" aria-hidden="true"><circle className="report-ring-track" cx="92" cy="92" r="76"/><circle className="report-ring-value" cx="92" cy="92" r="76" strokeDasharray={circumference} strokeDashoffset={circumference*(1-(score||0)/100)}/></svg><div><strong>{score??'—'}</strong><span>sur 100</span></div></div>;
}
function Metric({label,value,description,tone='rose'}:{label:string;value:number|null;description:string;tone?:string}){
 return <div className={'report-metric '+tone}><span>{label}</span><div className="report-meter" aria-hidden="true"><i style={{width:(value??0)+'%'}}/></div><strong>{value??'—'}{value!==null&&<small>/100</small>}</strong><p>{description}</p></div>;
}
export function ReadingAnalysis({analysis,title,onRetry}:{analysis:any;title?:string;onRetry?:()=>void}){
 const data=reportData(analysis),phonetic=isPhonetic(analysis),score=data.score;
 const [selected,setSelected]=useState<number|null>(null),[playing,setPlaying]=useState(false),[speechError,setSpeechError]=useState('');
 const [showAll,setShowAll]=useState(false),[phoneOpen,setPhoneOpen]=useState(false);
 const generation=useRef(0),ownsSpeech=useRef(false),currentSpeech=useRef(''),panelId=useId();
 useEffect(()=>()=>{generation.current++;if(ownsSpeech.current)window.speechSynthesis?.cancel()},[]);
 function speak(text:string,stopIfPlaying=false){
  setSpeechError('');
  if(!window.speechSynthesis){setSpeechError('L’écoute nécessite une voix française disponible dans votre navigateur.');return;}
  const synthesis=window.speechSynthesis,wasPlaying=playing;
  generation.current++;synthesis.cancel();ownsSpeech.current=false;setPlaying(false);
  if(wasPlaying&&(stopIfPlaying||currentSpeech.current===text))return;
  currentSpeech.current=text;
  const current=generation.current,voices=synthesis.getVoices(),voice=voices.find(v=>v.lang==='fr-FR')||voices.find(v=>v.lang.startsWith('fr'));
  const words=text.split(/\s+/).filter(Boolean),chunks:string[]=[];for(let i=0;i<words.length;i+=25)chunks.push(words.slice(i,i+25).join(' '));
  let index=0;ownsSpeech.current=true;setPlaying(true);
  const next=()=>{if(current!==generation.current)return;if(index===chunks.length){setPlaying(false);ownsSpeech.current=false;return;}const utterance=new SpeechSynthesisUtterance(chunks[index++]);utterance.lang='fr-FR';utterance.rate=.85;if(voice)utterance.voice=voice;utterance.onend=next;utterance.onerror=()=>{if(current===generation.current){setPlaying(false);ownsSpeech.current=false;setSpeechError('La voix française est indisponible. Réessayez ou choisissez une autre voix dans le lecteur.');}};synthesis.speak(utterance)};
  if(synthesis.paused)synthesis.resume();next();
 }
 const tone=(score??0)>=75?'sage':(score??0)>=45?'lavender':'rose';
 const badge=score===null?'Analyse indisponible':score>=75?(phonetic?'Sons bien représentés':'Texte bien représenté'):score>=45?'Continuez à pratiquer':'Une lecture à retravailler';
 const activeWord=selected===null?null:data.words[selected];
 const visiblePractice=showAll?data.practice:data.practice.slice(0,8);
 const extraPhones=data.phones.filter(phone=>phone.status==='added');
 const tips=Array.isArray(analysis?.tips)?[...new Set<string>(analysis.tips.filter((tip:any)=>typeof tip==='string'&&tip.trim()).map((tip:string)=>tip.replaceAll('le modèle a détecté','le son repéré est')))]:[];
 return <section className={'reading-report tone-'+tone} aria-label="Votre bilan de lecture">
  <header className="report-heading"><span className="report-overline"><Sparkles size={15}/> VOTRE LECTURE, PAS À PAS</span><h3>{phonetic?'Votre bilan de prononciation':'Votre bilan de lecture'}</h3><p>{phonetic?'Les points clés de votre lecture':'Comparaison avec le passage lu'}{analysis?.passage?` · Passage ${analysis.passage}`:''}</p></header>
  <ScoreRing score={score} label={phonetic?'Indice phonétique':'Fidélité au texte'}/><span className="report-status">{badge}</span>
  <div className="report-metrics">{phonetic?<><Metric label="Complétude" value={data.completion} description="Sons attendus détectés" tone="sage"/><Metric label="Précision" value={data.precision} description="Sons détectés identiques au passage" tone="lavender"/><Metric label="Fluidité" value={null} description={`${analysis.timing?.pauseCount||0} pauses mesurées · score non calibré`} tone="blue"/><Metric label="Prononciation" value={score} description="Repérage des sons dans votre lecture"/></>:<><Metric label="Fidélité au texte" value={score} description="Comparaison des mots transcrits"/><div className="report-metric blue"><span>Vitesse de lecture</span><strong>{analysis?.wordsPerMinute??'—'}</strong><p>Mots reconnus par minute</p></div></>}</div>
  {phonetic&&<div className="report-counts"><div><strong>{data.recognizedWords}</strong><span>Mots bien reconnus</span></div><div><strong>{data.words.length}</strong><span>Mots du passage</span></div><div><strong>{data.practice.length}</strong><span>Mots à revoir</span></div></div>}
  {data.reference&&<section className="report-passage"><div className="report-section-title"><span>{title||'Votre passage'}</span><span>{data.words.length} mots</span></div>{phonetic&&<div className="report-legend"><span><i className="recognized"/> Bien reconnu</span><span><i className="uncertain"/> À réécouter</span><span><i className="missing"/> Non reconnu</span></div>}<p className="report-highlighted-text">{data.segments.map((segment,i)=>segment.word&&phonetic?<button type="button" key={i} className={'report-text-word '+segment.word.status+(selected===segment.word.index?' active':'')} onClick={()=>setSelected(selected===segment.word!.index?null:segment.word!.index)} aria-pressed={selected===segment.word.index} aria-controls={panelId} title={segment.word.status==='recognized'?'Sons bien reconnus':segment.word.status==='missing'?'Sons non reconnus':segment.word.status==='unavailable'?'Mesure individuelle indisponible':'Sons à réécouter'}>{segment.text}</button>:<span key={i}>{segment.text}</span>)}</p><p className="report-passage-help">{phonetic?'Touchez un mot pour explorer ses sons. La couleur indique les sons repérés dans votre lecture.':'Ce résultat historique compare la transcription au texte.'}</p>{activeWord&&<div className="report-selected-word" id={panelId}><div><strong>{activeWord.text}</strong><button className="report-word-listen" onClick={()=>speak(activeWord.text)} aria-label={'Écouter '+activeWord.text}><Volume2 size={17}/></button></div><p>{activeWord.status==='recognized'?'Les sons de ce mot ont été bien repérés dans votre lecture.':activeWord.status==='unavailable'?'Cette ancienne analyse ne permet pas de séparer les sons de cette occurrence du mot.':wordFeedback(activeWord)}</p><Phones word={activeWord}/>{activeWord.pause!==null&&<small>Pause mesurée après ce mot : {decimal(activeWord.pause)} s. Une pause de ponctuation peut être naturelle.</small>}</div>}</section>}
  {phonetic&&<section className="report-practice"><h4><AlertCircle size={18}/> Mots à pratiquer <span>{data.practice.length}</span></h4>{visiblePractice.length?<ul>{visiblePractice.map(word=><li key={word.index}><span className={'report-issue '+(word.status==='missing'?'missing':'uncertain')}>{word.status==='missing'?'Non reconnu':'Prononciation'}</span><div><button className="report-practice-word" onClick={()=>setSelected(word.index)}>{word.text}</button><p>{wordFeedback(word)}</p>{selected===word.index&&<Phones word={word}/>}</div><button className="report-word-listen" onClick={()=>speak(word.text)} aria-label={'Écouter '+word.text}><Volume2 size={17}/></button></li>)}</ul>:<p className="report-positive"><Check size={18}/> Aucun mot à retravailler repéré dans cette lecture.</p>}{data.practice.length>8&&<button className="report-expand" onClick={()=>setShowAll(!showAll)}>{showAll?'Réduire la liste':`Voir les ${data.practice.length} mots à revoir`}<ChevronDown size={16}/></button>}</section>}
  {phonetic&&<section className="report-insight rhythm"><h4><Activity size={19}/> Rythme et pauses</h4><div className="report-timing"><span><b>{decimal(analysis.timing?.voicedSeconds)}</b> s de voix</span><span><b>{analysis.timing?.pauseCount||0}</b> pauses</span><span><b>{decimal(analysis.timing?.pauseSeconds)}</b> s de pauses</span></div><p>{analysis.timing?.pauseCount?'Des silences d’au moins 0,3 seconde ont été repérés. Écoutez-les dans votre lecture et entraînez-vous à lire par groupes de mots. Les pauses de ponctuation restent naturelles.':'Aucun silence de 0,3 seconde ou plus n’a été repéré entre les segments de voix.'}</p>{(analysis.timing?.clipped||analysis.timing?.noiseHigh)&&<p>Le son semble saturé ou bruyant : refaites une lecture dans un endroit calme.</p>}</section>}
  <section className="report-insight advice"><h4><Lightbulb size={19}/> Conseils d’amélioration</h4>{tips.length?<ul>{tips.map(tip=><li key={tip}>{tip}</li>)}</ul>:<p>Écoutez la lecture de référence, puis répétez une phrase à la fois avant de refaire votre lecture.</p>}</section>
  {phonetic&&<details className="report-phonemes" open={phoneOpen} onToggle={e=>setPhoneOpen(e.currentTarget.open)}><summary><Volume2 size={18}/> Détail des phonèmes <ChevronDown size={17}/></summary><p>Retrouvez les sons à réécouter et à pratiquer dans chaque mot. La qualité de votre enregistrement peut influencer ces repères.</p>{phoneOpen&&<div className="report-word-grid">{data.words.filter(w=>w.phones.length).map(word=><div key={word.index} className="report-phone-word"><strong>{word.text}</strong><Phones word={word}/></div>)}</div>}{phoneOpen&&extraPhones.length>0&&<div className="report-phone-word"><strong>Sons supplémentaires détectés</strong><Phones word={{index:-1,text:"Sons supplémentaires",phones:extraPhones,status:"unavailable",confidence:null,pause:null}}/></div>}</details>}
  {!phonetic&&analysis?.differences?.length>0&&<details className="report-phonemes"><summary>Écarts dans la transcription <ChevronDown size={17}/></summary><ul>{analysis.differences.map((difference:any,i:number)=><li key={i}>{difference.kind==='missing'?`Non reconnu : ${difference.expected}`:difference.kind==='added'?`Ajout reconnu : ${difference.heard}`:`Attendu : ${difference.expected} · reconnu : ${difference.heard}`}</li>)}</ul></details>}
  <footer className="report-footer">{data.reference&&<><p>Écoutez la lecture de référence, puis essayez à votre rythme.</p><button className="report-listen-button" onClick={()=>speak(data.reference,true)}>{playing?<Square size={18}/>:<Headphones size={19}/>} {playing?'Arrêter l’écoute':'Écouter la lecture de référence'}</button></>}{onRetry&&<button className="report-retry-button" onClick={onRetry}><RotateCcw size={17}/> Refaire ma lecture</button>}{speechError&&<p className="report-speech-error" role="status">{speechError}</p>}<details className="report-method"><summary><ShieldCheck size={15}/> Comprendre ces mesures</summary><p>{phonetic?'Ces repères vous aident à identifier les sons à pratiquer. Ils peuvent varier selon la qualité de l’enregistrement et ne constituent pas une évaluation certifiée de l’accent, de la fluidité ou du niveau de français.':'Cette séance utilise une comparaison de transcription, sans mesure des phonèmes, de l’accent ou de la fluidité. Faites une nouvelle lecture pour obtenir une analyse acoustique.'}</p></details></footer>
 </section>;
}
function Phones({word}:{word:ReportWord}){return <div className="report-phone-chips">{word.phones.map((phone,i)=><div className={'report-phone-chip '+(phone.status==='missing'?'missing':phone.status==='different'||(phone.confidence??0)<55?'uncertain':'recognized')} key={i}><b>/{phone.expected||phone.heard}/</b><span>{phone.status==='added'?'Son supplémentaire':phone.confidence===null?'Non reconnu':phone.confidence+' %'}</span>{phone.status==='different'&&<small>Détecté : /{phone.heard}/</small>}{phone.start!==null&&<small>{decimal(phone.start)}–{decimal(phone.end??phone.start)} s</small>}</div>)}</div>}
