'use client';
import {useState} from 'react';
import {BookOpen,Target,NotebookPen,BarChart3,Headphones,Mic,Check,Clock,User,GraduationCap,Briefcase,MessageCircle,ShieldCheck,Menu,X,Leaf,Globe,Sparkles,Gift,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {articles,plans} from './content';
export function Brand({footer=false}: {footer?:boolean}){return <a href="#accueil" className={footer?'brand brand-footer':'brand'} aria-label="MimFlo — accueil"><img src="/assets/mimflo-logo-pastel.png" alt="MimFlo — Votre voix, votre plus belle progression !" width="2168" height="725"/></a>}
const navs=[['accueil','Accueil'],['bibliotheque','Bibliothèque'],['parcours','Mes parcours'],['progression','Ma progression'],['notes','Mes notes'],['packs','Abonnements']];
export default function Welcome({go}: {go:(view:string,articleId?:string)=>void}){
 const [menu,setMenu]=useState(false);
 const featured=['climat','reseaux','travail'].map(id=>articles.find(a=>a.id===id)!);
 return <div className="site welcome-page">
 <header className="header"><Brand/><nav>{navs.map(([v,label])=><button key={v} onClick={()=>go(v)} className={v==='accueil'?'active':''}>{label}</button>)}</nav><div className="header-actions"><Button className="btn secondary" onClick={()=>go('profil')}><User/>Mon espace</Button><button className="menu-trigger" aria-label="Ouvrir le menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="expanded-menu">{[...navs,['aide','Aide & FAQ']].map(([v,label])=><button key={v} onClick={()=>{setMenu(false);go(v)}}>{label}</button>)}</div>}</header>
 <main className="main">
 <section className="free-trial-banner" aria-label="Essayez MimFlo gratuitement"><div className="trial-banner-title"><span className="trial-banner-gift" aria-hidden="true"><Gift/></span><div><h2>Essayez gratuitement !</h2><p>1 article · 1 entraînement <span>48h</span></p></div><span className="trial-banner-rays" aria-hidden="true"><i/><i/><i/></span></div><p className="trial-banner-copy">Découvrez la méthode MimFlo et faites le premier pas vers une meilleure prononciation !</p><Button className="btn trial-banner-button" onClick={()=>go('essai')}>Commencer mon essai gratuit <ArrowRight aria-hidden="true"/></Button></section>
 <section className="hero"><div className="hero-copy"><span className="eyebrow"><span/> CHAQUE VOIX A SON HISTOIRE</span><h1>Parlez avec confiance,<br/><em>atteignez vos objectifs.</em></h1><p>Des entraînements de prononciation et d’expression orale pour vous aider à parler naturellement, à votre rythme, et en toute confiance.</p><div className="actions"><Button className="btn" onClick={()=>go('inscription')}>Inscription <ArrowRight aria-hidden="true"/></Button></div><div className="hero-proof"><span><Check/>Première séance offerte</span><span><Clock/>48 h pour essayer</span></div></div><div className="hero-art"><div className="hero-circle"/><img src="/assets/hero-study.png" alt="Une jeune femme étudie avec des livres et un jeune homme sans casque travaille sur son ordinateur" width="1774" height="887" fetchPriority="high"/><span className="handwriting hero-note">Chaque voix compte.</span></div></section>
 <section className="journey" aria-label="Votre préparation avec MimFlo">{[[GraduationCap,'Examen proche','Une préparation ciblée'],[Target,'Entraînement intensif','Des exercices qui font la différence'],[NotebookPen,'Répétition et pratique','Un petit pas, chaque jour'],[BarChart3,'Votre progression','Vos efforts deviennent visibles']].map(([Icon,title,desc]:any,i)=><div key={title}><span className={'icon-tile color-'+i}><Icon/></span><h3>{title}</h3><p>{desc}</p></div>)}</section>
 <section className="home-section"><div className="home-section-heading"><div><span className="eyebrow">UN OBJECTIF, VOTRE PARCOURS</span><h2>Votre français, pour la vraie vie.</h2><p>Un examen, un entretien ou simplement l’envie de vous exprimer plus librement.</p></div><span className="handwriting">À chacun sa voix,<br/>à chacun son rythme.</span></div><div className="goal-grid">{[[GraduationCap,'Préparer un examen','TCF, TEF, DELF ou DALF : entraînez-vous à prendre la parole et à organiser vos idées.','Préparer mon oral','blue'],[Briefcase,'Parler au travail','Présentez votre parcours, partagez vos idées et prenez votre place dans la conversation.','Gagner en aisance','sage'],[MessageCircle,'Prendre confiance','Lisez à voix haute, découvrez de nouvelles expressions et osez parler au quotidien.','Trouver mon rythme','lilac']].map(([Icon,title,copy,label,tone]:any)=><article className={'goal-card tone-'+tone} key={title}><span className="goal-icon"><Icon/></span><h3>{title}</h3><p>{copy}</p><button className="text-link" onClick={()=>go('parcours')}>{label}</button></article>)}</div></section>
 <section className="home-section method-section"><div className="method-intro"><span className="eyebrow">UNE ROUTINE SIMPLE À ADOPTER</span><h2>Écoutez.<br/><em>Parlez.</em><br/>Recommencez.</h2><p>Faites de chaque lecture un petit entraînement. Quelques minutes pour écouter, essayer et enrichir votre vocabulaire.</p><Button className="btn blue" onClick={()=>go('article','reseaux')}>Découvrir une séance</Button></div><div className="method-steps">{[[Headphones,'01','Écoutez le modèle','Découvrez le texte et écoutez sa lecture pour vous familiariser avec les sons et le rythme.'],[Mic,'02','À vous de prendre la parole','Enregistrez votre lecture, réécoutez-vous et comparez avec le modèle, sans pression.'],[NotebookPen,'03','Gardez les mots qui comptent','Ajoutez les expressions utiles à vos notes et retrouvez votre activité dans votre espace.']].map(([Icon,n,title,copy]:any)=><div className="method-step" key={n}><span className="step-icon"><Icon/></span><div><span className="step-number">{n}</span><h3>{title}</h3><p>{copy}</p></div></div>)}</div></section>
 <section className="home-section"><div className="home-section-heading"><div><span className="eyebrow">DES SUJETS QUI VOUS PARLENT</span><h2>Une nouvelle lecture, une nouvelle idée.</h2><p>Du quotidien aux grands sujets de société : choisissez ce qui vous intéresse.</p></div><Button className="btn secondary" onClick={()=>go('bibliotheque')}>Toute la bibliothèque</Button></div><div className="featured-articles">{featured.map((article,i)=>{const Icon=[Leaf,Globe,Briefcase][i];return <article className={'featured-article tone-'+['sage','lilac','blue'][i]} key={article.id}><div className="topic-header"><span className="pill">{article.category}</span><Icon/></div><h3>{article.title}</h3><p>{article.intro}</p><div className="featured-meta"><span>Niveau {article.level}</span><span><Clock/>{article.minutes} min</span></div><button className="text-link" onClick={()=>go('article',article.id)}>Lire et m’entraîner</button></article>})}</div><div className="topic-links"><span>Et aussi :</span>{['Voyage','Culture','Vie quotidienne','Technologie','Éducation'].map(c=><button key={c} onClick={()=>go('bibliotheque')}>{c}</button>)}</div></section>
 <section className="home-section home-cards"><article className="card trial-card"><div><span className="tag">VOTRE PREMIER PAS</span><h2>Votre première séance<br/><em>est offerte !</em></h2><ul className="check-list"><li><Check/>1 article à découvrir</li><li><Check/>1 entraînement à enregistrer</li><li><Check/>48 heures pour essayer</li></ul><Button className="btn" onClick={()=>go('essai')}>Commencer mon essai gratuit</Button></div><img src="/assets/mascot.png" alt="La mascotte MimFlo vous encourage" loading="lazy"/></article><article className="card daily-card"><span className="icon-tile color-0"><ShieldCheck/></span><h3>Votre espace, vos progrès.</h3><p>Retrouvez vos séances, votre temps de pratique et les mots que vous avez sauvegardés. Un carnet qui grandit avec vous.</p><div className="space-features"><span><User/>Mon profil</span><span><NotebookPen/>Mes notes</span><span><BarChart3/>Mon suivi</span></div><Button className="btn blue" onClick={()=>go('inscription')}>Créer mon profil</Button></article></section>
 <section className="home-section home-plans"><div className="home-section-heading"><div><span className="eyebrow">UN COUP DE POUCE POUR VOTRE OBJECTIF</span><h2>Trois rythmes de préparation.</h2><p>Choisissez la formule qui correspond à votre temps et à votre objectif.</p></div><Button className="btn secondary" onClick={()=>go('packs')}>Comparer les formules</Button></div><div className="home-plan-grid">{plans.map((plan,i)=><article key={plan.id} className={'home-plan tone-'+['blue','lilac','sage'][i]}>{i===1&&<span className="plan-label">Le plus choisi</span>}<span className="section-overline">{plan.name}</span><h3>{plan.days} <span>jours</span></h3><p>{plan.features.join(' · ')}</p><div className="home-plan-bottom"><strong>{plan.price} €</strong><button className="text-link" onClick={()=>go('packs')}>Voir le pack</button></div></article>)}</div><p className="home-payment-note">Les packs payants ne sont pas encore disponibles à l’achat. Votre première séance est offerte.</p></section>
 <section className="home-section home-faq"><div><span className="eyebrow">AVANT DE VOUS LANCER</span><h2>Tout commence par<br/>un premier mot.</h2><p>Les réponses aux questions les plus fréquentes.</p><button className="text-link" onClick={()=>go('aide')}>Consulter toute l’aide</button></div><div className="faq-items">{[['Quel niveau faut-il avoir ?','La bibliothèque propose des articles de niveau A1 à B2. Choisissez un sujet et un niveau qui vous mettent à l’aise.'],['Comment fonctionne la première séance ?','Créez votre profil puis démarrez votre essai. Vous disposez de 48 heures pour réaliser une lecture enregistrée.'],['Mes notes et ma progression sont-elles sauvegardées ?','Oui, votre profil, vos notes et vos séances sauvegardées sont conservés dans votre espace personnel.'],['Puis-je écouter et enregistrer depuis mon téléphone ?','Oui, avec un navigateur compatible et l’autorisation du microphone. La lecture vocale et la transcription dépendent du navigateur utilisé.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
 <section className="home-final"><div><span className="eyebrow">UN MOT APRÈS L’AUTRE</span><h2>Votre voix a sa place.<br/>Donnez-lui confiance.</h2><p>Votre première séance vous attend.</p></div><Button className="btn blue" onClick={()=>go('essai')}>Essayer MimFlo gratuitement</Button></section>
 </main><footer><div className="footer-identity"><Brand footer/><span className="handwriting">Plus qu’un site,<br/>une vraie préparation !</span></div><div className="footer-links"><button onClick={()=>go('bibliotheque')}>Bibliothèque</button><button onClick={()=>go('packs')}>Abonnements</button><button onClick={()=>go('notes')}>Mes notes</button><button onClick={()=>go('aide')}>Aide & confidentialité</button></div></footer>
 </div>
}
