import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { articles } from '@/app/content';
export const dynamic='force-dynamic';
function db(){if(!env.DB)throw new Error('Storage unavailable');return env.DB;}
function fail(error:unknown){console.error('MimFlo storage',error);return Response.json({error:'La sauvegarde est indisponible. Réessayez dans un instant.'},{status:503});}
function short(value:unknown,max:number){return typeof value==='string'?value.trim().slice(0,max):'';}
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({user:null,profile:null,notes:[],sessions:[]});try{const d=db();const [profile,notes,sessions]=await Promise.all([d.prepare('SELECT * FROM profiles WHERE user_id=?').bind(user.userId).first(),d.prepare('SELECT id,word,definition,created_at FROM notes WHERE user_id=? ORDER BY created_at DESC').bind(user.userId).all(),d.prepare('SELECT id,article_id,seconds,transcript,coverage,created_at FROM sessions WHERE user_id=? ORDER BY created_at DESC LIMIT 200').bind(user.userId).all()]);return Response.json({user:{name:user.fullName,email:user.email},profile,notes:notes.results,sessions:sessions.results});}catch(error){return fail(error)}}
export async function POST(request:Request){
 const user=await getChatGPTUser();if(!user)return Response.json({error:'Connectez-vous pour sauvegarder votre progression.'},{status:401});
 const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)return Response.json({error:'Requête refusée.'},{status:403});
 let b:any;try{if(Number(request.headers.get('content-length')||0)>24000)throw 0;b=await request.json()}catch{return Response.json({error:'Données invalides.'},{status:400})}
 try{const d=db(),uid=user.userId,now=Date.now();
 if(b.action==='profile'){const first=short(b.firstName,60),last=short(b.lastName,60),level=short(b.level,10),exam=short(b.exam,40),source=short(b.source,80);if(!first||!last||!['A1','A2','B1','B2','C1','C2'].includes(level)||!b.consent)return Response.json({error:'Complétez votre prénom, nom, niveau et acceptez les conditions.'},{status:400});await d.prepare('INSERT INTO profiles (user_id,first_name,last_name,level,exam,source,created_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET first_name=excluded.first_name,last_name=excluded.last_name,level=excluded.level,exam=excluded.exam,source=excluded.source').bind(uid,first,last,level,exam,source,now).run();return Response.json({ok:true});}
 const p:any=await d.prepare('SELECT * FROM profiles WHERE user_id=?').bind(uid).first();if(!p)return Response.json({error:'Créez votre profil pour commencer.'},{status:409});
 if(b.action==='trial'){await d.prepare('UPDATE profiles SET trial_at=COALESCE(trial_at,?) WHERE user_id=?').bind(now,uid).run();return Response.json({ok:true});}
 if(b.action==='note'){const word=short(b.word,100),definition=short(b.definition,1000);if(!word||!definition)return Response.json({error:'Ajoutez un mot et sa définition.'},{status:400});const id=crypto.randomUUID();await d.prepare('INSERT INTO notes (id,user_id,word,definition,created_at) VALUES (?,?,?,?,?)').bind(id,uid,word,definition,now).run();return Response.json({ok:true,id});}
 if(b.action==='deleteNote'){await d.prepare('DELETE FROM notes WHERE id=? AND user_id=?').bind(short(b.id,50),uid).run();return Response.json({ok:true});}
 if(b.action==='plan'){if(!['sprint','intensif','performance'].includes(b.plan))return Response.json({error:'Pack invalide.'},{status:400});await d.prepare('UPDATE profiles SET selected_plan=? WHERE user_id=?').bind(b.plan,uid).run();return Response.json({ok:true});}
 if(b.action==='session'){const aid=short(b.articleId,50),seconds=Math.round(Number(b.seconds));if(!articles.some(a=>a.id===aid)||!Number.isFinite(seconds)||seconds<3||seconds>1800)return Response.json({error:'Enregistrez au moins trois secondes, jusqu’à 30 minutes.'},{status:400});if(!p.trial_at||now-p.trial_at>48*3600000)return Response.json({error:'Votre essai est terminé. Consultez les packs pour la suite.'},{status:403});const previous:any=await d.prepare('SELECT COUNT(*) AS total FROM sessions WHERE user_id=?').bind(uid).first();if(previous.total>=1)return Response.json({error:'Votre entraînement offert est déjà terminé.'},{status:403});const transcript=short(b.transcript,16000),article=articles.find(a=>a.id===aid)!;const norm=(s:string):string[]=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').match(/[a-z]+/g)||[];const expected=norm(article.paragraphs.join(' ')),spoken=norm(transcript);let found=0,j=0;for(const word of expected){const at=spoken.indexOf(word,j);if(at>=0){found++;j=at+1}}const coverage=transcript?Math.round(found/expected.length*100):null;await d.prepare('INSERT INTO sessions (id,user_id,article_id,seconds,transcript,coverage,created_at) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),uid,aid,seconds,transcript,coverage,now).run();return Response.json({ok:true,coverage});}
 return Response.json({error:'Action inconnue.'},{status:400});}catch(error){return fail(error)}
}
